-- 원본 테이블
DROP TABLE TEMP;
CREATE TABLE TEMP(
    TITLE VARCHAR2(100)
    , CONTENT VARCHAR2(4000)
);

-- 행 삽입시, 복사할 테이블
DROP TABLE TEMP_COPY;
CREATE TABLE TEMP_COPY(
    TITLE VARCHAR2(100)
    , CONTENT VARCHAR2(4000)
);

-- 행 삭제시, 삭제된 데이터 저장할 테이블
DROP TABLE TEMP_TRASH;
CREATE TABLE TEMP_TRASH(
    TITLE VARCHAR2(100)
    , CONTENT VARCHAR2(4000)
);

-- 테이블 수정 시, 기록 남기기 위한 테이블
DROP TABLE TEMP_LOG;
CREATE TABLE TEMP_LOG(
    TITLE VARCHAR2(100)
    , CONTENT VARCHAR2(4000)
);


-- 현재 테이블에 DML이 몇번 호출되었는지 카운트하는 테이블
DROP TABLE TEMP_DML_CNT;
CREATE TABLE TEMP_DML_CNT(
    CNT NUMBER
);