CREATE OR REPLACE TRIGGER TRG_TEMP_DML_CNT
AFTER INSERT OR DELETE OR UPDATE ON TEMP
    BEGIN
        INSERT INTO TEMP_DML_CNT(CNT) VALUES(NVL((SELECT MAX(CNT) FROM TEMP_DML_CNT),0)+1);
        DELETE TEMP_DML_CNT WHERE CNT != (SELECT MAX(CNT) FROM TEMP_DML_CNT);
END TRG_TEMP;