-- DML 테스트
INSERT INTO TEMP(TITLE, CONTENT) VALUES('제목3','내용3');
UPDATE TEMP SET CONTENT = '내용변경~' WHERE TITLE = '제목1';
UPDATE TEMP SET CONTENT = '한번더변경' WHERE TITLE = '제목1';
DELETE TEMP WHERE TITLE = '제목1';

SELECT * FROM TEMP;
SELECT * FROM TEMP_COPY;
SELECT * FROM TEMP_LOG;
SELECT * FROM TEMP_TRASH;
SELECT * FROM TEMP_DML_CNT;

-- 조회
SELECT '===원본===' AS 제목 ,'===원본===' AS 내용 FROM DUAL
UNION ALL
SELECT * FROM TEMP
UNION ALL
SELECT '===사본===' AS 제목 ,'===사본===' FROM DUAL
UNION ALL
SELECT * FROM TEMP_COPY
UNION ALL
SELECT '===기록===' AS 제목 ,'===기록===' FROM DUAL
UNION ALL
SELECT * FROM TEMP_LOG
UNION ALL
SELECT '===삭제===' AS 제목 ,'===삭제===' FROM DUAL
UNION ALL
SELECT * FROM TEMP_TRASH
UNION ALL
SELECT '========' AS 제목 ,'========' FROM DUAL
UNION ALL
SELECT 'DML횟수' ,TO_CHAR(CNT) FROM TEMP_DML_CNT
;