--final_test

-- MEMBER
DROP SEQUENCE SEQ_MEMBER;
CREATE SEQUENCE SEQ_MEMBER NOCACHE NOCYCLE;

DROP TABLE MEMBER CASCADE CONSTRAINTS;
CREATE TABLE MEMBER(
    NO              NUMBER          PRIMARY KEY
    , ID            VARCHAR2(100)   NOT NULL UNIQUE
    , PWD           VARCHAR2(100)   NOT NULL
    , NICK          VARCHAR2(100)   NOT NULL
    , ENROLL_DATE   TIMESTAMP       DEFAULT SYSDATE
    , MODIFY_DATE   TIMESTAMP       
    , DEL_YN        CHAR(1)         DEFAULT 'N' CHECK( DEL_YN IN ('Y' , 'N') )
);

-- ADMIN
DROP SEQUENCE SEQ_ADMIN;
CREATE SEQUENCE SEQ_ADMIN NOCACHE NOCYCLE;

DROP TABLE ADMIN CASCADE CONSTRAINTS;
CREATE TABLE ADMIN(
    NO              NUMBER          PRIMARY KEY
    , ID            VARCHAR2(100)   NOT NULL UNIQUE
    , PWD           VARCHAR2(100)   NOT NULL
    , NICK          VARCHAR2(100)   NOT NULL
    , ENROLL_DATE   TIMESTAMP       DEFAULT SYSDATE
    , MODIFY_DATE   TIMESTAMP       
    , DEL_YN        CHAR(1)         DEFAULT 'N' CHECK( DEL_YN IN ('Y' , 'N') )
);

-- GALLERY
DROP SEQUENCE SEQ_GALLERY;
CREATE SEQUENCE SEQ_GALLERY NOCYCLE NOCACHE;

DROP TABLE GALLERY CASCADE CONSTRAINTS;
CREATE TABLE GALLERY(
    NO              NUMBER          PRIMARY KEY
    ,WRITER_NO      NUMBER          NOT NULL --외래키는 나중에 ,,,
    ,TITLE          VARCHAR2(100)   NOT NULL
    ,CONTENT        VARCHAR2(4000)  NOT NULL
    ,ENROLL_DATE    TIMESTAMP       DEFAULT SYSDATE
    ,ORIGIN_NAME    VARCHAR2(1000)  
    ,FILE_URL       VARCHAR2(1000)
    ,DEL_YN        CHAR(1)         DEFAULT 'N' CHECK( DEL_YN IN ('Y' , 'N') )
);


-- LIKE
DROP TABLE MEMBER_GALLERY_LIKE CASCADE CONSTRAINTS;
CREATE TABLE MEMBER_GALLERY_LIKE( --외래키는 나중에 ,,,
    WRITER_NO NUMBER
    , GALLERY_NO NUMBER
);



BEGIN
    FOR i IN 1..10 LOOP
        INSERT INTO ADMIN (NO, ID, PWD, NICK) 
        VALUES (SEQ_ADMIN.NEXTVAL, 'admin' || i, '$2a$10$VTF5b9fypZL7cAo89/OzbugB0/Adw7M7wpEuG3rr418iiQagjuN2W', '관리자' || i);
    END LOOP;
    COMMIT;
END;
/

BEGIN
    FOR i IN 1..123 LOOP
        INSERT INTO GALLERY (NO, WRITER_NO, TITLE, CONTENT, ENROLL_DATE, ORIGIN_NAME, FILE_URL, DEL_YN) 
        VALUES (SEQ_GALLERY.NEXTVAL, 0, i || ' 번째 갤러리', '콘텐츠ㅋㅋㅋ', SYSDATE, 'image.png', 'https://picsum.photos/300/200', 'N');
    END LOOP;
    COMMIT;
END;
/



