-- <MEMBER> 
DROP SEQUENCE SEQ_MEMBER; 
CREATE SEQUENCE SEQ_MEMBER NOCYCLE NOCACHE;

DROP TABLE MEMBER CASCADE CONSTRAINTS;
CREATE TABLE MEMBER (
    NO              NUMBER          PRIMARY KEY
    , ID            VARCHAR2(100)   NOT NULL UNIQUE
    , PWD           VARCHAR2(100)   NOT NULL
    , NICK          VARCHAR2(100)   NOT NULL
    , ENROLL_DATE   TIMESTAMP       DEFAULT SYSDATE
    , MODIFY_DATE   TIMESTAMP
    , DEL_YN        CHAR(1)         DEFAULT 'N' CHECK ( DEL_YN IN ('Y', 'N') )
    , PROFILE       VARCHAR2(1000)
);


-- <BOARD>
DROP SEQUENCE SEQ_BOARD;
CREATE SEQUENCE SEQ_BOARD NOCYCLE NOCACHE;

DROP TABLE BOARD CASCADE CONSTRAINTS;
CREATE TABLE BOARD (
    NO              NUMBER          PRIMARY KEY
    , TITLE         VARCHAR2(100)   NOT NULL
    , CONTENT       VARCHAR2(100)   NOT NULL
    , WRITER_NO     NUMBER          NOT NULL
    , HIT           NUMBER          DEFAULT 0 
    , ENROLL_DATE   TIMESTAMP       DEFAULT SYSDATE
    , MODIFY_DATE   TIMESTAMP
    , DEL_YN        CHAR(1)         DEFAULT 'N' CHECK ( DEL_YN IN ('Y', 'N') )
);

-- 제약조건(외래키) 추가
ALTER TABLE BOARD ADD CONSTRAINT FK_BOARD_MEMBER FOREIGN KEY(WRITER_NO) REFERENCES MEMBER(NO);

SELECT * FROM BOARD;
SELECT * FROM MEMBER;

-- <MEMBER 기능>
-- 회원가입
INSERT INTO MEMBER (
    NO
    , ID
    , PWD
    , NICK
) 
VALUES 
(
    SEQ_MEMBER.NEXTVAL
    , ? 
    , ?
    , ?
)
;

-- 로그인
SELECT *
FROM MEMBER
WHERE ID = ?
AND PWD = ?
AND DEL_YN = 'N' 
;

-- 비밀번호 수정 (기존 비밀번호 확인, 새 비밀번호 설정)
UPDATE MEMBER
SET PWD = ?
    , MODIFY_DATE = SYSDATE
WHERE NO = ? 
AND PWD = ? 
;

-- 닉네임 수정
UPDATE MEMBER
SET NICK = ?
    , MODIFY_DATE = SYSDATE
WHERE NO = ? 
;

-- 회원탈퇴 (비밀번호 확인 후 탈퇴 처리)
UPDATE MEMBER
SET DEL_YN = 'Y'
    , MODIFY_DATE = SYSDATE
WHERE NO = ? 
AND PWD = ? 
;

-- 전체 회원 목록 조회 (관리자)
SELECT * 
FROM MEMBER
ORDER BY NO DESC;

-- 회원 상세 조회 (관리자)
SELECT * 
FROM MEMBER
WHERE ID = ? ;

-- <BOARD 기능>
-- 게시글 작성
INSERT INTO BOARD (
    NO
    , TITLE
    , CONTENT
    , WRITER_NO
) VALUES (
    SEQ_BOARD.NEXTVAL
    , ?
    , ?
    , ?
)
;

-- 게시글 제목 수정
UPDATE BOARD 
SET TITLE = ?
    , MODIFY_DATE = SYSDATE
WHERE NO = ? 
AND WRITER_NO = ? ;

-- 게시글 내용 수정
UPDATE BOARD 
SET CONTENT = ?
    , MODIFY_DATE = SYSDATE
WHERE NO = ? 
AND WRITER_NO = ? ;

-- 게시글 삭제
UPDATE BOARD
SET DEL_YN = 'Y'
    , MODIFY_DATE = SYSDATE
WHERE NO = ? 
AND WRITER_NO = ? 
;

-- 게시글 조회수 증가
UPDATE BOARD
SET HIT = HIT + 1
WHERE NO = ? ;

-- 게시글 목록 조회
SELECT B.NO
    , B.TITLE
    , B.CONTENT
    , B.WRITER_NO
    , M.NICK    AS WRITER_NICK
    , B.HIT
    , B.ENROLL_DATE
    , B.MODIFY_Date
    , B.DEL_YN
FROM BOARD B
JOIN MEMBER M ON (B.WRITER_NO = M.NO)
WHERE B.DEL_YN = 'N'
ORDER BY B.NO DESC
;

-- 게시글 상세 조회
SELECT *
FROM BOARD
WHERE NO = ? 
AND DEL_YN = 'N';

-- 게시글 검색 (제목)
SELECT *
FROM BOARD
WHERE TITLE LIKE '%' || ? || '%'
AND DEL_YN = 'N';

-- 게시글 검색 (내용)
SELECT *
FROM BOARD
WHERE CONTENT LIKE '%' || ? || '%'
AND DEL_YN = 'N';

-- 게시글 검색 (작성자)
-- 닉네임으로 번호 얻기
SELECT *
FROM BOARD
WHERE WRITER_NO IN (
    SELECT NO
    FROM MEMBER
    WHERE NICK LIKE '%nick%'
    AND DEL_YN = 'N'
    )
;

COMMIT;




SELECT 
		B.NO
		, B.TITLE
		, B.CONTENT
		, B.WRITER_NO
		, M.NICK			AS WRITER_NICK
		, B.HIT
		, B.ENROLL_DATE
		, B.MODIFY_Date
		, B.DEL_YN
	FROM BOARD B
	JOIN MEMBER M ON (B.WRITER_NO = M.NO)
	WHERE B.DEL_YN = 'N'
	ORDER BY B.NO DESC
    
    
