-- TABLE
DROP TABLE BOARD CASCADE CONSTRAINTS;
CREATE TABLE BOARD (
    NO              NUMBER          CONSTRAINT BOARD_NO_PK PRIMARY KEY
    , TITLE         VARCHAR2(100)   CONSTRAINT BOARD_TITLE_NN NOT NULL
    , CONTENT       VARCHAR2(100)   CONSTRAINT BOARD_CONTENT_NN NOT NULL
    , ENROLL_DATE   TIMESTAMP       DEFAULT SYSDATE
);

-- SEQUENCE
DROP SEQUENCE SEQ_BOARD;
CREATE SEQUENCE SEQ_BOARD NOCYCLE NOCACHE;

-- INSERT
INSERT INTO BOARD (NO, TITLE, CONTENT) VALUES (SEQ_BOARD.NEXTVAL, ? , ? ); 

-- UPDATE
UPDATE BOARD 
SET TITLE = ?
    , CONTENT = ? 
WHERE NO = ? ;

-- DELETE
DELETE BOARD
WHERE NO = ? ;

-- SELECT (목록조회)
SELECT * FROM BOARD
ORDER BY NO;

-- SELECT (상세조회)
SELECT *
FROM BOARD
WHERE NO = ? ;

DROP SEQUENCE SEQ_BOARD;
DROP TABLE BOARD;
DELETE BOARD;

-----------------------------------------------------------------------

-- TABLE
CREATE TABLE MEMBER (
    NO              NUMBER          CONSTRAINT MEMBER_NO_PK PRIMARY KEY
    , NAME          VARCHAR2(50)    CONSTRAINT MEMBER_NAME_NN NOT NULL
    , BIRTH_DATE    VARCHAR2(8)    CONSTRAINT MEMBER_BIRTH_DATE_NN NOT NULL CONSTRAINT MEMBER_BIRTH_DATE_CK CHECK ( LENGTH(BIRTH_DATE) = 8 )
    , PHONE         VARCHAR2(50)
    , ADDRESS       VARCHAR2(100)
    , ENROLL_DATE   TIMESTAMP       DEFAULT SYSDATE
);

-- SEQUENCE
CREATE SEQUENCE MEMBER_SEQ NOCYCLE NOCACHE;

-- INSERT 
INSERT INTO MEMBER(NO, NAME, BIRTH_DATE, PHONE, ADDRESS) VALUES ( MEMBER_SEQ.NEXTVAL, ?, ?, ?, ? );

-- UPDATE
UPDATE MEMBER
SET 
    NAME = ?
    , PHONE = ?
    , ADDRESS = ?
WHERE NO = ? ;

-- DELETE
DELETE MEMBER
WHERE NO = ?;

-- SELECT (전체 회원 조회)
SELECT LPAD(NO, 4, 0) AS NO
    , NAME
    , BIRTH_DATE
    , NVL(PHONE, '미등록') AS PHONE
    , NVL(ADDRESS, '미등록') AS ADDRESS
    , TO_CHAR(ENROLL_DATE, 'YY/MM/DD HH24:MM:SS') AS ENROLL_DATE
FROM MEMBER;

-- SELECT (회원 번호로 검색)
SELECT LPAD(NO, 4, 0) AS NO
    , NAME
    , BIRTH_DATE
    , NVL(PHONE, '미등록') AS PHONE
    , NVL(ADDRESS, '미등록') AS ADDRESS
    , TO_CHAR(ENROLL_DATE, 'YY/MM/DD HH24:MM:SS')
FROM MEMBER
WHERE NO = 1 ;

-- SELECT (회원 이름로 검색)
SELECT LPAD(NO, 4, 0) AS NO
    , NAME
    , BIRTH_DATE
    , PHONE 
    , ADDRESS
    , TO_CHAR(ENROLL_DATE, 'YY/MM/DD HH24:MM:SS')
FROM MEMBER
WHERE NAME LIKE ? ;


-- SELECT (회원 전화번호로 검색)
SELECT LPAD(NO, 4, 0) AS NO
    , NAME
    , BIRTH_DATE
    , PHONE 
    , ADDRESS
    , TO_CHAR(ENROLL_DATE, 'YY/MM/DD HH24:MM:SS')
FROM MEMBER
WHERE PHONE LIKE ? ;

-- DROP
DROP TABLE MEMBER;
DROP SEQUENCE MEMBER_SEQ;