-- ITEM TABLE
DROP TABLE ITEM CASCADE CONSTRAINTS;
CREATE TABLE ITEM (
    NO              NUMBER          PRIMARY KEY
    , NAME          VARCHAR2(100)   NOT NULL
    , PRICE         VARCHAR2(100)   NOT NULL
    , ENROLL_DATE   TIMESTAMP       DEFAULT SYSDATE
);

-- ITEM SEQUENCE
DROP SEQUENCE SEQ_ITEM;
CREATE SEQUENCE SEQ_ITEM NOCYCLE NOCACHE;

-- MEMBER TABLE
DROP TABLE MEMBER CASCADE CONSTRAINTS;
CREATE TABLE MEMBER (
    NO              NUMBER          PRIMARY KEY
    , ID            VARCHAR2(100)   NOT NULL UNIQUE
    , PASSWORD      VARCHAR2(100)   NOT NULL
    , NICKNAME      VARCHAR2(100)   NOT NULL
    , ENROLL_DATE   TIMESTAMP       DEFAULT SYSDATE
);

-- MEMBER SEQUENCE
DROP SEQUENCE SEQ_MEMBER;
CREATE SEQUENCE SEQ_MEMBER NOCYCLE NOCACHE;