---------------------------------------------------
---------------------- 삭제 ------------------------
---------------------------------------------------
DROP SEQUENCE SEQ_MEMBER;
DROP SEQUENCE SEQ_ADMIN;
DROP SEQUENCE SEQ_BOARD;
DROP SEQUENCE SEQ_BOARD_ATTACHMENT;
DROP SEQUENCE SEQ_NOTICE;
DROP SEQUENCE SEQ_REPLY;
DROP SEQUENCE SEQ_CATEGORY;

DROP TABLE MEMBER CASCADE CONSTRAINTS;
DROP TABLE ADMIN CASCADE CONSTRAINTS;
DROP TABLE BOARD CASCADE CONSTRAINTS;
DROP TABLE BOARD_ATTACHMENT CASCADE CONSTRAINTS;
DROP TABLE NOTICE CASCADE CONSTRAINTS;
DROP TABLE BOARD_REPLY CASCADE CONSTRAINTS;
DROP TABLE CATEGORY CASCADE CONSTRAINTS;

---------------------------------------------------
--------------------- 시퀀스 -----------------------
---------------------------------------------------
CREATE SEQUENCE SEQ_MEMBER              NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_ADMIN               NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_BOARD               NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_BOARD_ATTACHMENT    NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_NOTICE              NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_REPLY               NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_CATEGORY            NOCACHE NOCYCLE;

CREATE SEQUENCE SEQ_NOTICE_REPLY        NOCACHE NOCYCLE;

---------------------------------------------------
--------------------- 테이블 -----------------------
---------------------------------------------------
CREATE TABLE MEMBER(
    NO          NUMBER          PRIMARY KEY
    , ID        VARCHAR2(100)   NOT NULL UNIQUE
    , PWD       VARCHAR2(100)   NOT NULL
    , NICK      VARCHAR2(100)   NOT NULL UNIQUE
    , PROFILE   VARCHAR2(4000)
    , DEL_YN    CHAR(1)         DEFAULT 'N' CHECK(DEL_YN IN ('Y','N'))
    , ENROLL_DATE TIMESTAMP     DEFAULT SYSDATE
    , MODIFY_DATE TIMESTAMP 
);

CREATE TABLE ADMIN(
    NO          NUMBER          PRIMARY KEY
    , ID        VARCHAR2(100)   NOT NULL UNIQUE
    , PWD       VARCHAR2(100)   NOT NULL
    , NICK      VARCHAR2(100)   NOT NULL UNIQUE
    , DEL_YN    CHAR(1)         DEFAULT 'N' CHECK(DEL_YN IN ('Y','N'))
);

CREATE TABLE BOARD(
    NO              NUMBER          PRIMARY KEY
    , TITLE         VARCHAR2(1000)  NOT NULL
    , CONTENT       VARCHAR2(4000)  NOT NULL
    , CATEGORY_NO   NUMBER          
    , WRITER_NO     NUMBER          NOT NULL
    , HIT           NUMBER          DEFAULT 0
    , CREATE_DATE   TIMESTAMP       DEFAULT SYSDATE
    , DEL_YN        CHAR(1)         DEFAULT 'N' CHECK(DEL_YN IN ('Y','N'))
);

CREATE TABLE BOARD_ATTACHMENT(
    NO              NUMBER          PRIMARY KEY
    , REF_NO        NUMBER          NOT NULL
    , ORIGIN_NAME   VARCHAR2(255)   
    , CHANGE_NAME   VARCHAR2(255)   NOT NULL UNIQUE
    , UPLOAD_DATE   TIMESTAMP       DEFAULT SYSDATE
    , DEL_YN        CHAR(1)         DEFAULT 'N'
);

CREATE TABLE NOTICE(
    NO              NUMBER          PRIMARY KEY
    , TITLE         VARCHAR2(1000)  NOT NULL
    , CONTENT       VARCHAR2(4000)  NOT NULL
    , WRITER_NO     NUMBER          NOT NULL
    , HIT           NUMBER          DEFAULT 0
    , CREATE_DATE   TIMESTAMP       DEFAULT SYSDATE
    , DEL_YN        CHAR(1)         DEFAULT 'N' CHECK(DEL_YN IN ('Y','N'))
);

CREATE TABLE BOARD_REPLY(
    NO              NUMBER          PRIMARY KEY
    , CONTENT       VARCHAR2(4000)  NOT NULL
    , REF_NO        NUMBER          NOT NULL
    , WRITER_NO     NUMBER          NOT NULL
    , CREATE_DATE   TIMESTAMP       DEFAULT SYSDATE
    , DEL_YN        CHAR(1)         DEFAULT 'N' CHECK(DEL_YN IN ('Y','N'))
);

CREATE TABLE CATEGORY(
    NO              NUMBER          PRIMARY KEY
    , NAME          VARCHAR2(30)    NOT NULL UNIQUE
);

CREATE TABLE NOTICE_REPLY(
    NO              NUMBER          PRIMARY KEY
    , CONTENT       VARCHAR2(4000)  NOT NULL
    , REF_NO        NUMBER          NOT NULL
    , WRITER_NO     NUMBER          NOT NULL
    , CREATE_DATE   TIMESTAMP       DEFAULT SYSDATE
    , DEL_YN        CHAR(1)         DEFAULT 'N' CHECK(DEL_YN IN ('Y','N'))
);

---------------------------------------------------
--------------------- 외래키 -----------------------
---------------------------------------------------
ALTER TABLE NOTICE ADD CONSTRAINT FK_NOTICE_BOARD FOREIGN KEY (WRITER_NO) REFERENCES ADMIN(NO);
ALTER TABLE BOARD ADD CONSTRAINT FK_BOARD_MEMBER FOREIGN KEY (WRITER_NO) REFERENCES MEMBER(NO);
ALTER TABLE BOARD ADD CONSTRAINT FK_BOARD_CATEGORY FOREIGN KEY (CATEGORY_NO) REFERENCES CATEGORY(NO);
ALTER TABLE BOARD_ATTACHMENT ADD CONSTRAINT FK_BOARD_ATTACHMENT_BOARD FOREIGN KEY (REF_NO) REFERENCES BOARD(NO);
ALTER TABLE BOARD_REPLY ADD CONSTRAINT FK_BOARD_REPLY_BOARD FOREIGN KEY (REF_NO) REFERENCES BOARD(NO);
ALTER TABLE BOARD_REPLY ADD CONSTRAINT FK_BOARD_REPLY_MEMBER FOREIGN KEY (WRITER_NO) REFERENCES MEMBER(NO);

ALTER TABLE NOTICE_REPLY ADD CONSTRAINT FK_NOTICE_REPLY_NOTICE FOREIGN KEY (REF_NO) REFERENCES NOTICE(NO);
ALTER TABLE NOTICE_REPLY ADD CONSTRAINT FK_NOTICE_REPLY_MEMBER FOREIGN KEY (WRITER_NO) REFERENCES MEMBER(NO);

---------------------------------------------------
--------------------- 데이터 -----------------------
---------------------------------------------------
INSERT INTO ADMIN(NO, ID, PWD, NICK) VALUES(SEQ_ADMIN.NEXTVAL, 'master' , '1234', '마스터');
INSERT INTO ADMIN(NO, ID, PWD, NICK) VALUES(SEQ_ADMIN.NEXTVAL, 'admin' , '1234', '운영자');
INSERT INTO ADMIN(NO, ID, PWD, NICK) VALUES(SEQ_ADMIN.NEXTVAL, 'admin01' , '1234', '운영자1');
INSERT INTO ADMIN(NO, ID, PWD, NICK) VALUES(SEQ_ADMIN.NEXTVAL, 'admin02' , '1234', '운영자2');
INSERT INTO ADMIN(NO, ID, PWD, NICK) VALUES(SEQ_ADMIN.NEXTVAL, 'admin031' , '1234', '운영자3');
COMMIT;

INSERT INTO CATEGORY(NO, NAME) VALUES(SEQ_CATEGORY.NEXTVAL, '자유');
INSERT INTO CATEGORY(NO, NAME) VALUES(SEQ_CATEGORY.NEXTVAL, '운동');
INSERT INTO CATEGORY(NO, NAME) VALUES(SEQ_CATEGORY.NEXTVAL, '게임');
INSERT INTO CATEGORY(NO, NAME) VALUES(SEQ_CATEGORY.NEXTVAL, '개발');
INSERT INTO CATEGORY(NO, NAME) VALUES(SEQ_CATEGORY.NEXTVAL, '자바');
INSERT INTO CATEGORY(NO, NAME) VALUES(SEQ_CATEGORY.NEXTVAL, '코딩');
INSERT INTO CATEGORY(NO, NAME) VALUES(SEQ_CATEGORY.NEXTVAL, '낚시');
INSERT INTO CATEGORY(NO, NAME) VALUES(SEQ_CATEGORY.NEXTVAL, '요리');
INSERT INTO CATEGORY(NO, NAME) VALUES(SEQ_CATEGORY.NEXTVAL, '댄스');
INSERT INTO CATEGORY(NO, NAME) VALUES(SEQ_CATEGORY.NEXTVAL, '기타');
COMMIT;

-- 함수

-- SEQ_BOARD_ATTACHMENT.NEXTVAL 얻어오는 함수

CREATE OR REPLACE FUNCTION GET_BAROD_ATTACHMENT_NO
RETURN NUMBER
AS  
    N NUMBER; -- 선언부
BEGIN -- 실행부

    SELECT SEQ_BOARD_ATTACHMENT.NEXTVAL -- SELECT로 값 뽑아와서 INTO 안에다 넣겠다
    INTO N    -- 그럼 ABC에 위 실행결과가 들어가게 됨
    FROM DUAL;

RETURN N;
END 
;
/

SELECT SEQ_BOARD_ATTACHMENT.NEXTVAL
FROM DUAL;
    
SELECT SEQ_BOARD_ATTACHMENT.CURRVAL
FROM DUAL;