---------------------------------------------------
---------------------- 삭제 ------------------------
---------------------------------------------------
DROP TABLE "EMPLOYEE" CASCADE CONSTRAINTS;
DROP TABLE "EMP_STATUS" CASCADE CONSTRAINTS;
DROP TABLE "VACATION_LOG" CASCADE CONSTRAINTS;
DROP TABLE "DEPARTMENT" CASCADE CONSTRAINTS;
DROP TABLE "SALARY" CASCADE CONSTRAINTS;
DROP TABLE "POSITION" CASCADE CONSTRAINTS;
DROP TABLE "PRODUCT_REGISTRATION" CASCADE CONSTRAINTS;
DROP TABLE "INSPECTION_HISTORY" CASCADE CONSTRAINTS;
DROP TABLE "DEFECTIVE_CODE" CASCADE CONSTRAINTS;
DROP TABLE "VACATION_TYPE" CASCADE CONSTRAINTS;
DROP TABLE "DEFECTIVE_PRODUCT" CASCADE CONSTRAINTS;
DROP TABLE "INSPECTION_STATUS" CASCADE CONSTRAINTS;
DROP TABLE "AS_REQUEST" CASCADE CONSTRAINTS;
DROP TABLE "OVERTIME" CASCADE CONSTRAINTS;
DROP TABLE "INSPECTION_TYPE" CASCADE CONSTRAINTS;
DROP TABLE "FAULT_CODE" CASCADE CONSTRAINTS;
DROP TABLE "PARTNER" CASCADE CONSTRAINTS;
DROP TABLE "SALE" CASCADE CONSTRAINTS;
DROP TABLE "EXPENSE" CASCADE CONSTRAINTS;
DROP TABLE "BALANCESHEET" CASCADE CONSTRAINTS;
DROP TABLE "AS_WORK" CASCADE CONSTRAINTS;
DROP TABLE "ACCOUNT" CASCADE CONSTRAINTS;
DROP TABLE "TRANS_ITEM" CASCADE CONSTRAINTS;
DROP TABLE "PURCHASE" CASCADE CONSTRAINTS;
DROP TABLE "PRODUCT_INQUIRY" CASCADE CONSTRAINTS;
DROP TABLE "AS_ENGINEERS" CASCADE CONSTRAINTS;
DROP TABLE "DEFECTIVE_IMAGES" CASCADE CONSTRAINTS;
DROP TABLE "ATTENDANCE" CASCADE CONSTRAINTS;
DROP TABLE "SALARY_PAYMENT" CASCADE CONSTRAINTS;
DROP TABLE "BANK" CASCADE CONSTRAINTS;
DROP TABLE "AS_STATUS" CASCADE CONSTRAINTS;
DROP TABLE "ADMIN" CASCADE CONSTRAINTS;
DROP TABLE "BUSINESS_TYPE" CASCADE CONSTRAINTS;
DROP TABLE "EXPENSE_ATTACHMENT" CASCADE CONSTRAINTS;
DROP TABLE "SALE_ATTACHMENT" CASCADE CONSTRAINTS;
DROP TABLE "PURCHASE_ATTACHMENT" CASCADE CONSTRAINTS;
DROP TABLE "SALARY_ATTACHMENT" CASCADE CONSTRAINTS;
DROP TABLE "INCOMESTATEMENT" CASCADE CONSTRAINTS;


---------------------------------------------------
--------------------- DROP시퀀스 -----------------------
---------------------------------------------------
DROP SEQUENCE SEQ_EMPLOYEE;
DROP SEQUENCE SEQ_EMP_STATUS;
DROP SEQUENCE SEQ_VACATION_LOG;
DROP SEQUENCE SEQ_DEPARTMENT;
DROP SEQUENCE SEQ_SALARY;
DROP SEQUENCE SEQ_POSITION;
DROP SEQUENCE SEQ_PRODUCT_REGISTRATION;
DROP SEQUENCE SEQ_INSPECTION_HISTORY;
DROP SEQUENCE SEQ_DEFECTIVE_CODE;
DROP SEQUENCE SEQ_VACATION_TYPE;
DROP SEQUENCE SEQ_DEFECTIVE_PRODUCT;
DROP SEQUENCE SEQ_INSPECTION_STATUS;
DROP SEQUENCE SEQ_AS_REQUEST;
DROP SEQUENCE SEQ_OVERTIME;
DROP SEQUENCE SEQ_INSPECTION_TYPE;
DROP SEQUENCE SEQ_FAULT_CODE;
DROP SEQUENCE SEQ_PARTNER;
DROP SEQUENCE SEQ_SALE;
DROP SEQUENCE SEQ_EXPENSE;
DROP SEQUENCE SEQ_BALANCESHEET;
DROP SEQUENCE SEQ_AS_WORK;
DROP SEQUENCE SEQ_ACCOUNT;
DROP SEQUENCE SEQ_TRANS_ITEM;
DROP SEQUENCE SEQ_PURCHASE;
DROP SEQUENCE SEQ_PRODUCT_INQUIRY;
DROP SEQUENCE SEQ_SERIAL_NUMBER;
DROP SEQUENCE SEQ_DEFECTIVE_IMAGES;
DROP SEQUENCE SEQ_ATTENDANCE;
DROP SEQUENCE SEQ_SALARY_PAYMENT;
DROP SEQUENCE SEQ_BANK;
DROP SEQUENCE SEQ_AS_STATUS;
DROP SEQUENCE SEQ_ADMIN;
DROP SEQUENCE SEQ_BUSINESS_TYPE;
DROP SEQUENCE SEQ_EXPENSE_ATTACHMENT;
DROP SEQUENCE SEQ_SALE_ATTACHMENT;
DROP SEQUENCE SEQ_PURCHASE_ATTACHMENT;
DROP SEQUENCE SEQ_SALARY_ATTACHMENT;
DROP SEQUENCE SEQ_INCOMESTATEMENT;

---------------------------------------------------
--------------------- CREATE시퀀스 -----------------------
---------------------------------------------------
CREATE SEQUENCE SEQ_EMPLOYEE NOCYCLE NOCACHE;
CREATE SEQUENCE SEQ_EMP_STATUS NOCYCLE NOCACHE;
CREATE SEQUENCE SEQ_VACATION_LOG NOCYCLE NOCACHE;
CREATE SEQUENCE SEQ_DEPARTMENT NOCYCLE NOCACHE;
CREATE SEQUENCE SEQ_SALARY NOCYCLE NOCACHE;
CREATE SEQUENCE SEQ_POSITION NOCYCLE NOCACHE;
CREATE SEQUENCE SEQ_PRODUCT_REGISTRATION NOCYCLE NOCACHE;
CREATE SEQUENCE SEQ_INSPECTION_HISTORY NOCYCLE NOCACHE;
CREATE SEQUENCE SEQ_DEFECTIVE_CODE NOCYCLE NOCACHE;
CREATE SEQUENCE SEQ_VACATION_TYPE NOCYCLE NOCACHE;
CREATE SEQUENCE SEQ_DEFECTIVE_PRODUCT NOCYCLE NOCACHE;
CREATE SEQUENCE SEQ_INSPECTION_STATUS NOCYCLE NOCACHE;
CREATE SEQUENCE SEQ_AS_REQUEST NOCYCLE NOCACHE;
CREATE SEQUENCE SEQ_OVERTIME NOCYCLE NOCACHE;
CREATE SEQUENCE SEQ_INSPECTION_TYPE NOCYCLE NOCACHE;
CREATE SEQUENCE SEQ_FAULT_CODE NOCYCLE NOCACHE;
CREATE SEQUENCE SEQ_PARTNER NOCYCLE NOCACHE;
CREATE SEQUENCE SEQ_SALE NOCYCLE NOCACHE;
CREATE SEQUENCE SEQ_EXPENSE NOCYCLE NOCACHE;
CREATE SEQUENCE SEQ_BALANCESHEET NOCYCLE NOCACHE;
CREATE SEQUENCE SEQ_AS_WORK NOCYCLE NOCACHE;
CREATE SEQUENCE SEQ_ACCOUNT NOCYCLE NOCACHE;
CREATE SEQUENCE SEQ_TRANS_ITEM NOCYCLE NOCACHE;
CREATE SEQUENCE SEQ_PURCHASE NOCYCLE NOCACHE;
CREATE SEQUENCE SEQ_PRODUCT_INQUIRY NOCYCLE NOCACHE;
CREATE SEQUENCE SEQ_SERIAL_NUMBER NOCYCLE NOCACHE;
CREATE SEQUENCE SEQ_DEFECTIVE_IMAGES NOCYCLE NOCACHE;
CREATE SEQUENCE SEQ_ATTENDANCE NOCYCLE NOCACHE;
CREATE SEQUENCE SEQ_SALARY_PAYMENT NOCYCLE NOCACHE;
CREATE SEQUENCE SEQ_BANK NOCYCLE NOCACHE;
CREATE SEQUENCE SEQ_AS_STATUS NOCYCLE NOCACHE;
CREATE SEQUENCE SEQ_ADMIN NOCYCLE NOCACHE;
CREATE SEQUENCE SEQ_BUSINESS_TYPE NOCYCLE NOCACHE;
CREATE SEQUENCE SEQ_EXPENSE_ATTACHMENT NOCYCLE NOCACHE;
CREATE SEQUENCE SEQ_SALE_ATTACHMENT NOCYCLE NOCACHE;
CREATE SEQUENCE SEQ_PURCHASE_ATTACHMENT NOCYCLE NOCACHE;
CREATE SEQUENCE SEQ_SALARY_ATTACHMENT NOCYCLE NOCACHE;
CREATE SEQUENCE SEQ_INCOMESTATEMENT NOCYCLE NOCACHE;

---------------------------------------------------
--------------------- 테이블 -----------------------
---------------------------------------------------
CREATE TABLE "EMPLOYEE" (
   "NO"   NUMBER      NOT NULL,
   "PROFILE_IMAGE"   VARCHAR2(300)      NOT NULL,
   "PWD"   VARCHAR2(200)   DEFAULT 1111   NOT NULL,
   "NAME"   VARCHAR2(20)      NOT NULL,
   "BIRTH"   CHAR(8)      NOT NULL,
   "GENDER"   CHAR(1) CHECK(GENDER IN ('F','M'))   NOT NULL,
   "EMAIL"   VARCHAR2(50)      NOT NULL,
   "PHONE"   CHAR(12)      NOT NULL,
   "EMERGENCY_PHONE"   CHAR(11)      NULL,
   "ADDRESS"   VARCHAR2(100)      NULL,
   "DEPT_CODE"   NUMBER      NULL,
   "POSITION_CODE"   NUMBER      NULL,
   "SALARY"   NUMBER      NOT NULL,
   "BANK_CODE"   NUMBER      NOT NULL,
   "ACCOUNT_NO"   VARCHAR2(50)      NOT NULL,
   "TOTAL_VACATION_DAYS"   NUMBER      NOT NULL,
   "STATUS_CODE"   NUMBER      NOT NULL,
   "ENTER_DATE"   CHAR(8)      NOT NULL,
   "OUT_DATE"   CHAR(8)      NULL,
   "ENROLL_DATE"   TIMESTAMP   DEFAULT SYSDATE   NULL,
   "MODIFY_DATE"   TIMESTAMP      NULL,
   "DEL_YN"    CHAR(1) DEFAULT 'N'  CHECK(DEL_YN IN('Y','N')) NOT   NULL
);

    
CREATE TABLE "EMP_STATUS" (
   "NO"   NUMBER      NOT NULL,
   "NAME"   VARCHAR2(10)      NOT NULL
);
CREATE TABLE "VACATION_LOG" (
   "NO"   NUMBER      NOT NULL,
   "EMP_NO"   NUMBER      NOT NULL,
   "CODE"   NUMBER      NOT NULL,
   "THISDATE"   CHAR(10)      NOT NULL,
   "REASON"   VARCHAR2(100)      NULL,
   "ENROLL_DATE"   TIMESTAMP   DEFAULT SYSDATE   NULL,
   "MODIFY_DATE"   TIMESTAMP      NULL,
   "DEL_YN"   CHAR(1) DEFAULT 'N'  CHECK(DEL_YN IN('Y','N'))   NOT   NULL
);
CREATE TABLE "DEPARTMENT" (
   "NO"   NUMBER      NOT NULL,
   "NAME"   VARCHAR2(20)      NOT NULL
);
CREATE TABLE "SALARY" (
   "NO"   NUMBER      NOT NULL,
   "EMP_NO"   NUMBER      NOT NULL,
   "PAY_YEARMONTH"   CHAR(6)      NOT NULL,
   "BASIC"   NUMBER      NULL,
   "MEAL_ALLOWANCE"   NUMBER      NOT NULL,
   "COMMUNICATION_COST"   NUMBER      NOT NULL,
   "NATIONAL_PENSION"   NUMBER      NOT NULL,
   "HEALTH_INSURANCE"   NUMBER      NOT NULL,
   "EMPLOYMENT_INSURANCE"   NUMBER      NOT NULL,
   "LONGTERM_CARE_INSURANCE"   NUMBER      NOT NULL,
   "INCOME_TAX"   NUMBER      NOT NULL,
   "LOCAL_TAXES"   NUMBER      NOT NULL,
    "DEL_YN"   CHAR(1) DEFAULT 'N'  CHECK(DEL_YN IN('Y','N'))   NOT   NULL
);
CREATE TABLE "POSITION" (
   "NO"   NUMBER      NOT NULL,
   "NAME"   VARCHAR2(10)      NOT NULL
);
CREATE TABLE "PRODUCT_REGISTRATION" (
   "NO"   NUMBER      NOT NULL,
   "ITEM_CODE"   NUMBER      NOT NULL,
   "NAME"   VARCHAR2(100)      NOT NULL,
   "SERIAL_NUMBER"   VARCHAR2(20)      NOT NULL,
   "PRICE"   NUMBER      NOT NULL,
   "WARRANTY_PERIOD"   VARCHAR2(2)      NOT NULL,
   "RECEIVED_DATE"   TIMESTAMP      NOT NULL,
   "FACTORY_NAME"   VARCHAR2(50)      NOT NULL,
    ITEM_IMAGE VARCHAR2(2000) NULL,
   "FACTORY_LOCATION"   VARCHAR2(100)      NOT NULL,
   "ENROLL_DATE"   TIMESTAMP   DEFAULT SYSDATE   NULL,
   "MODIFY_DATE"   TIMESTAMP      NULL,
   "DEL_YN"   CHAR(1) DEFAULT 'N'  CHECK(DEL_YN IN('Y','N'))   NOT   NULL
);
CREATE TABLE "INSPECTION_HISTORY" (
   "NO"   NUMBER      NOT NULL,
   "PRODUCT_NO"   NUMBER      NOT NULL,
   "INSPECTION_CODE"   NUMBER      NOT NULL,
   "SUCCESS_YN"   CHAR(1)    DEFAULT NULL NULL,
   "STATUS_CODE"   NUMBER      NOT NULL,
    INSPECTION_DATE CHAR(8) NOT NULL ,
   "ENROLL_DATE"   TIMESTAMP   DEFAULT SYSDATE   NULL,
   "MODIFY_DATE"   TIMESTAMP      NULL,
   "DEL_YN"   CHAR(1) DEFAULT 'N'  CHECK(DEL_YN IN('Y','N'))   NOT   NULL
);
CREATE TABLE "DEFECTIVE_CODE" (
   "NO"   NUMBER      NOT NULL,
   "NAME"   VARCHAR2(20)      NOT NULL
);
CREATE TABLE "VACATION_TYPE" (
   "NO"   NUMBER      NOT NULL,
   "NAME"   VARCHAR2(20)      NOT NULL
);
CREATE TABLE "DEFECTIVE_PRODUCT" (
   "NO"   NUMBER      NOT NULL,
   "P_NO"   NUMBER      NOT NULL,
   "DEFECTIVE_CODE"   NUMBER      NOT NULL,
   "DESCRIPTION"   VARCHAR2(200)      NULL,
   "ENROLL_DATE"   TIMESTAMP   DEFAULT SYSDATE   NULL,
   "MODIFY_DATE"   TIMESTAMP      NULL,
   "DEL_YN"   CHAR(1) DEFAULT 'N'  CHECK(DEL_YN IN('Y','N'))   NOT   NULL
);
CREATE TABLE "INSPECTION_STATUS" (
   "NO"   NUMBER      NOT NULL,
   "NAME"   VARCHAR2(20)      NOT NULL
);
CREATE TABLE "AS_REQUEST" (
   "NO"   NUMBER      NOT NULL,
   "P_NO"   NUMBER      NOT NULL,
   "CUSTOMER_NAME"   VARCHAR2(20)      NOT NULL,
    CUSTOMER_AREA VARCHAR2(100)       NOT NULL,
   "CUSTOMER_ADRESS"   VARCHAR2(100)      NOT NULL,
   "CUSTOMER_PHONE"   CHAR(11)      NOT NULL,
   "PURCHASE_DATE"   TIMESTAMP      NULL,
   "WARRANTY_YN"   CHAR(1) CHECK(WARRANTY_YN IN ('Y','N'))   NOT   NULL,
   "ISSUE_TITLE"   VARCHAR2(50)      NOT NULL,
   "ISSUE_DESCRIPTION"   VARCHAR2(1500)      NOT NULL,
   "PREFERRED_SERVICE_DATE"   TIMESTAMP      NULL,
   "STATUS_CODE"   NUMBER   DEFAULT 1   NOT NULL,
   "ENROLL_DATE"   TIMESTAMP   DEFAULT SYSDATE   NULL,
   "MODIFY_DATE"   TIMESTAMP      NULL,
   "DEL_YN"   CHAR(1) DEFAULT 'N'  CHECK(DEL_YN IN('Y','N'))   NOT   NULL
);
CREATE TABLE OVERTIME (
   NO   NUMBER      NOT NULL,
   EMP_NO   NUMBER      NULL,
   THISDATE   CHAR(10)      NOT NULL,
   TYPE   CHAR(12)      NOT NULL,
   WORK_HOUR   DATE      NOT NULL,
    "DEL_YN"   CHAR(1) DEFAULT 'N'  CHECK(DEL_YN IN('Y','N'))   NOT   NULL
);
CREATE TABLE "INSPECTION_TYPE" (
   "NO"   NUMBER      NOT NULL,
   "NAME"   VARCHAR2(20)      NOT NULL
);
CREATE TABLE "FAULT_CODE" (
   "NO"   NUMBER      NOT NULL,
   "NAME"   VARCHAR2(20)      NOT NULL,
    "DEL_YN"   CHAR(1) DEFAULT 'N'  CHECK(DEL_YN IN('Y','N'))   NOT   NULL
);
CREATE TABLE "PARTNER" (
   "NO"   NUMBER      NOT NULL,
   "BUSINESS_CODE"   NUMBER      NOT NULL,
   "NAME"   VARCHAR(200)      NOT NULL,
   "BIZ_REGIST_NO"   CHAR(10)      NOT NULL,
   "CEO_NAME"   VARCHAR(20)      NULL,
   "ADDRESS"   VARCHAR2(200)      NULL,
   "DEL_YN"   CHAR(1) DEFAULT 'N'  CHECK(DEL_YN IN('Y','N'))      NULL
);
CREATE TABLE "SALE" (
   "NO"   NUMBER      NOT NULL,
   "PARTNER_CODE"   NUMBER      NULL,
   "TRANS_CODE"   NUMBER      NOT NULL,
   "ACCOUNT_CODE"   NUMBER      NOT NULL,
   "TRANS_DATE"   CHAR(8)      NOT NULL,
   "SUPPLY_AMOUNT"   NUMBER      NOT NULL,
   "TAX_AMOUNT"   NUMBER      NOT NULL,
   "ATTACHMENT"   VARCHAR2(300)      NOT NULL,
   "COMMENTS"   VARCHAR2(200)      NULL,
   "ENROLL_DATE"   TIMESTAMP   DEFAULT SYSDATE   NULL,
   "MODIFY_DATE"   TIMESTAMP      NULL,
   "DEL_YN"   CHAR(1) DEFAULT 'N'  CHECK(DEL_YN IN('Y','N'))      NULL
);
CREATE TABLE "EXPENSE" (
   "NO"   NUMBER      NOT NULL,
   "PARTNER_CODE"   NUMBER      NULL,
   "TRANS_CODE"   NUMBER      NOT NULL,
   "ACCOUNT_CODE"   NUMBER      NOT NULL,
   "TRANS_DATE"   CHAR(8)      NOT NULL,
   "SUPPLY_AMOUNT"   NUMBER      NOT NULL,
   "TAX_AMOUNT"   NUMBER      NOT NULL,
   "ATTACHMENT"   VARCHAR2(300)      NOT NULL,
   "COMMENTS"   VARCHAR2(200)      NULL,
   "ENROLL_DATE"   TIMESTAMP   DEFAULT SYSDATE   NULL,
   "MODIFY_DATE"   TIMESTAMP      NULL,
   "DEL_YN"   CHAR(1) DEFAULT 'N'  CHECK(DEL_YN IN('Y','N'))      NULL
);
CREATE TABLE "BALANCESHEET" (
   "NO"   NUMBER      NOT NULL,
   "YEAR"   CHAR(4)      NOT NULL,
   "DEPOSIT"   NUMBER      NOT NULL,
   "PREPAID _TAX"   NUMBER      NOT NULL,
   "MERCHADISE"   NUMBER      NOT NULL,
   "RAW_MATERIAL"   NUMBER      NOT NULL,
   "WITHHOLDINGS"   NUMBER      NOT NULL,
   "WITHHELD_TAX"   NUMBER      NOT NULL,
   "CAPITAL_STOCK"   NUMBER      NOT NULL
);
CREATE TABLE "AS_WORK" (
   "NO"   NUMBER      NOT NULL,
   "AS_NO"   NUMBER      NOT NULL,
   "FAULT_CODE"   NUMBER      NULL,
   "EMP_NO"   NUMBER      NULL,
   "REPAIR_DATE"   CHAR(8)      NULL,
   "REPAIR_DETALIS"   VARCHAR2(200)      NULL,
   "ENROLL_DATE"   TIMESTAMP   DEFAULT SYSDATE   NULL,
   "MODIFY_DATE"   TIMESTAMP      NULL,
   "DEL_YN"   CHAR(1) DEFAULT 'N'  CHECK(DEL_YN IN('Y','N'))      NULL
);
CREATE TABLE "ACCOUNT" (
   "NO"   NUMBER      NOT NULL,
   "BANK_CODE"   NUMBER   NOT   NULL,
   "ACCOUNT_NAME"   VARCHAR2(20)   NOT   NULL,
   "ACCOUNT_NO"   VARCHAR2(20)      NOT NULL
);
CREATE TABLE "TRANS_ITEM" (
   "NO"   NUMBER      NOT NULL,
   "TYPE"   VARCHAR2(10)      NOT NULL,
   "NAME"   VARCHAR2(50)      NOT NULL
);
CREATE TABLE "PURCHASE" (
   "NO"   NUMBER      NOT NULL,
   "PARTNER_CODE"   NUMBER      NULL,
   "TRANS_CODE"   NUMBER      NOT NULL,
   "ACCOUNT_CODE"   NUMBER      NOT NULL,
   "TRANS_DATE"   CHAR(8)      NOT NULL,
   "SUPPLY_AMOUNT"   NUMBER      NOT NULL,
   "TAX_AMOUNT"   NUMBER      NOT NULL,
   "ATTACHMENT"   VARCHAR2(300)      NOT NULL,
   "COMMENTS"   VARCHAR2(200)      NULL,
   "ENROLL_DATE"   TIMESTAMP   DEFAULT SYSDATE   NULL,
   "MODIFY_DATE"   TIMESTAMP      NULL,
   "DEL_YN"   CHAR(1) DEFAULT 'N'  CHECK(DEL_YN IN('Y','N'))      NULL
);
CREATE TABLE "PRODUCT_INQUIRY" (
   "NO"   NUMBER      NOT NULL,
   "ITEM_NAME"   VARCHAR2(100)      NOT NULL
);
CREATE TABLE "AS_ENGINEERS" (
   "NO"   NUMBER      NOT NULL,
   "AREA"   VARCHAR2(20)      NOT NULL,
    "DEL_YN"   CHAR(1) DEFAULT 'N'  CHECK(DEL_YN IN('Y','N'))   NOT   NULL
);
CREATE TABLE "DEFECTIVE_IMAGES" (
   "NO"   NUMBER      NOT NULL,
   "REFNO"   NUMBER      NOT NULL,
   "PATH"   VARCHAR2(300)      NULL
);
CREATE TABLE "ATTENDANCE" (
   "NO"   NUMBER      NOT NULL,
   "EMP_NO"   NUMBER      NOT NULL,
   "CI_TIME"   TIMESTAMP      NULL,
   "CO_TIME"   TIMESTAMP      NULL,
   "DEL_YN"   CHAR(1) DEFAULT 'N'  CHECK(DEL_YN IN('Y','N'))   NULL
);
CREATE TABLE "SALARY_PAYMENT" (
   "NO"   NUMBER      NOT NULL,
   "TRANS_CODE"   NUMBER      NOT NULL,
   "ACCOUNT_CODE"   NUMBER      NOT NULL,
   "EMP_NO"   NUMBER      NOT NULL,
   "PAYMENT_DATE"   CHAR(8)      NOT NULL,
   "PAYMENT_YEAR_MONTH"   CHAR(6)      NOT NULL,
   "BASIC"   NUMBER      NOT NULL,
   "MEAL_ALLOWANCE"   NUMBER      NOT NULL,
   "COMMUNICATION_COST"   NUMBER      NOT NULL,
   "NIGHT_PAY"   NUMBER      NOT NULL,
   "WEEKEND_PAY"   NUMBER      NOT NULL,
   "EXTRA_PAY"   NUMBER      NOT NULL,
   "TOTAL_PAY"   NUMBER      NOT NULL,
   "NATIONAL_PENSION"   NUMBER      NOT NULL,
   "HEALTH_INSURANCE"   NUMBER      NOT NULL,
   "EMPLOYMENT_INSURANCE"   NUMBER      NOT NULL,
   "LONGTERM_CARE_INSURANCE"   NUMBER      NOT NULL,
   "INCOME_TAX"   NUMBER      NOT NULL,
   "LOCAL_TAXES"   NUMBER      NOT NULL,
   "EXTRA_DEDUCTION"   NUMBER      NOT NULL,
   "TOTAL_DEDUCTION"   NUMBER      NOT NULL,
   "NET_PAY"   NUMBER      NOT NULL,
   "ATTACHMENT"   VARCHAR2(300)      NULL,
   "COMMENTS"   VARCHAR2(200)      NULL,
   "ENROLL_DATE"   TIMESTAMP      NULL,
   "MODIFY_DATE"   TIMESTAMP      NULL,
   "DEL_YN"   CHAR(1) DEFAULT 'N'  CHECK(DEL_YN IN('Y','N'))      NULL
);
CREATE TABLE "BANK" (
   "NO"   NUMBER      NOT NULL,
   "NAME"   VARCHAR2(20)      NOT NULL
);
CREATE TABLE "AS_STATUS" (
   "NO"   NUMBER      NOT NULL,
   "NAME"   VARCHAR2(20)      NOT NULL
);
CREATE TABLE "ADMIN" (
   "NO"   NUMBER      NOT NULL,
   "EMAIL"   VARCHAR2(50)      NOT NULL,
   "PWD"   VARCHAR2(200)      NOT NULL
);
CREATE TABLE "BUSINESS_TYPE" (
   "NO"   NUMBER      NOT NULL,
   "BIZ_TYPE"   VARCHAR2(50)      NOT NULL,
   "BIZ_CATEGORY"   VARCHAR2(200)      NOT NULL
);
CREATE TABLE "EXPENSE_ATTACHMENT" (
   "NO"   NUMBER      NOT NULL,
   "EXPENSE_NO"   NUMBER      NOT NULL,
   "PATH"   VARCHAR2(300)      NULL
);
CREATE TABLE "SALE_ATTACHMENT" (
   "NO"   NUMBER      NOT NULL,
   "SALE_NO"   NUMBER      NOT NULL,
   "PATH"   VARCHAR2(300)      NULL
);
CREATE TABLE "PURCHASE_ATTACHMENT" (
   "NO"   NUMBER      NOT NULL,
   "PURCHASE_NO"   NUMBER      NOT NULL,
   "PATH"   VARCHAR2(300)      NULL
);
CREATE TABLE "SALARY_ATTACHMENT" (
   "NO"   NUMBER      NOT NULL,
   "PAYMENT_NO"   NUMBER      NOT NULL,
   "PATH"   VARCHAR2(300)      NULL
);
CREATE TABLE "INCOMESTATEMENT" (
   "NO"   NUMBER      NOT NULL,
   "YEAR"   CHAR(4)      NOT NULL,
   "SALES_MERCHANDISE"   NUMBER      NOT NULL,
   "SALES_GOODS"   NUMBER      NOT NULL,
   "SALARIES_EXPENSE"   NUMBER      NOT NULL,
   "TRAVEL_EXPENSE"   NUMBER      NOT NULL,
   "TAXES_DUES"   NUMBER      NOT NULL,
   "SUPPLIES_EXPENSE"   NUMBER      NOT NULL,
   "ADVERTISING"   NUMBER      NOT NULL
);


---------------------------------------------------
--------------------- 기본키/외래키 -----------------------
---------------------------------------------------
ALTER TABLE "EMPLOYEE" ADD CONSTRAINT "PK_EMPLOYEE" PRIMARY KEY (
   "NO"
);

ALTER TABLE "EMP_STATUS" ADD CONSTRAINT "PK_EMP_STATUS" PRIMARY KEY (
   "NO"
);

ALTER TABLE "VACATION_LOG" ADD CONSTRAINT "PK_VACATION_LOG" PRIMARY KEY (
   "NO"
);

ALTER TABLE "DEPARTMENT" ADD CONSTRAINT "PK_DEPARTMENT" PRIMARY KEY (
   "NO"
);

ALTER TABLE "SALARY" ADD CONSTRAINT "PK_SALARY" PRIMARY KEY (
   "NO"
);

ALTER TABLE "POSITION" ADD CONSTRAINT "PK_POSITION" PRIMARY KEY (
   "NO"
);

ALTER TABLE "PRODUCT_REGISTRATION" ADD CONSTRAINT "PK_PRODUCT_REGISTRATION" PRIMARY KEY (
   "NO"
);

ALTER TABLE "INSPECTION_HISTORY" ADD CONSTRAINT "PK_INSPECTION_HISTORY" PRIMARY KEY (
   "NO"
);

ALTER TABLE "DEFECTIVE_CODE" ADD CONSTRAINT "PK_DEFECTIVE_CODE" PRIMARY KEY (
   "NO"
);

ALTER TABLE "VACATION_TYPE" ADD CONSTRAINT "PK_VACATION_TYPE" PRIMARY KEY (
   "NO"
);

ALTER TABLE "DEFECTIVE_PRODUCT" ADD CONSTRAINT "PK_DEFECTIVE_PRODUCT" PRIMARY KEY (
   "NO"
);

ALTER TABLE "INSPECTION_STATUS" ADD CONSTRAINT "PK_INSPECTION_STATUS" PRIMARY KEY (
   "NO"
);

ALTER TABLE "AS_REQUEST" ADD CONSTRAINT "PK_AS_REQUEST" PRIMARY KEY (
   "NO"
);

ALTER TABLE "OVERTIME" ADD CONSTRAINT "PK_OVERTIME" PRIMARY KEY (
   "NO"
);

ALTER TABLE "INSPECTION_TYPE" ADD CONSTRAINT "PK_INSPECTION_TYPE" PRIMARY KEY (
   "NO"
);

ALTER TABLE "FAULT_CODE" ADD CONSTRAINT "PK_FAULT_CODE" PRIMARY KEY (
   "NO"
);

ALTER TABLE "PARTNER" ADD CONSTRAINT "PK_PARTNER" PRIMARY KEY (
   "NO"
);

ALTER TABLE "SALE" ADD CONSTRAINT "PK_SALE" PRIMARY KEY (
   "NO"
);

ALTER TABLE "EXPENSE" ADD CONSTRAINT "PK_EXPENSE" PRIMARY KEY (
   "NO"
);

ALTER TABLE "BALANCESHEET" ADD CONSTRAINT "PK_BALANCESHEET" PRIMARY KEY (
   "NO"
);

ALTER TABLE "AS_WORK" ADD CONSTRAINT "PK_AS_WORK" PRIMARY KEY (
   "NO"
);

ALTER TABLE "ACCOUNT" ADD CONSTRAINT "PK_ACCOUNT" PRIMARY KEY (
   "NO"
);

ALTER TABLE "TRANS_ITEM" ADD CONSTRAINT "PK_TRANS_ITEM" PRIMARY KEY (
   "NO"
);

ALTER TABLE "PURCHASE" ADD CONSTRAINT "PK_PURCHASE" PRIMARY KEY (
   "NO"
);

ALTER TABLE "PRODUCT_INQUIRY" ADD CONSTRAINT "PK_PRODUCT_INQUIRY" PRIMARY KEY (
   "NO"
);

ALTER TABLE "AS_ENGINEERS" ADD CONSTRAINT "PK_AS_ENGINEERS" PRIMARY KEY (
   "NO"
);

ALTER TABLE "DEFECTIVE_IMAGES" ADD CONSTRAINT "PK_DEFECTIVE_IMAGES" PRIMARY KEY (
   "NO"
);

ALTER TABLE "ATTENDANCE" ADD CONSTRAINT "PK_ATTENDANCE" PRIMARY KEY (
   "NO"
);

ALTER TABLE "SALARY_PAYMENT" ADD CONSTRAINT "PK_SALARY_PAYMENT" PRIMARY KEY (
   "NO"
);

ALTER TABLE "BANK" ADD CONSTRAINT "PK_BANK" PRIMARY KEY (
   "NO"
);

ALTER TABLE "AS_STATUS" ADD CONSTRAINT "PK_AS_STATUS" PRIMARY KEY (
   "NO"
);

ALTER TABLE "ADMIN" ADD CONSTRAINT "PK_ADMIN" PRIMARY KEY (
   "NO"
);

ALTER TABLE "BUSINESS_TYPE" ADD CONSTRAINT "PK_BUSINESS_TYPE" PRIMARY KEY (
   "NO"
);

ALTER TABLE "EXPENSE_ATTACHMENT" ADD CONSTRAINT "PK_EXPENSE_ATTACHMENT" PRIMARY KEY (
   "NO"
);

ALTER TABLE "SALE_ATTACHMENT" ADD CONSTRAINT "PK_SALE_ATTACHMENT" PRIMARY KEY (
   "NO"
);

ALTER TABLE "PURCHASE_ATTACHMENT" ADD CONSTRAINT "PK_PURCHASE_ATTACHMENT" PRIMARY KEY (
   "NO"
);

ALTER TABLE "SALARY_ATTACHMENT" ADD CONSTRAINT "PK_SALARY_ATTACHMENT" PRIMARY KEY (
   "NO"
);

ALTER TABLE "INCOMESTATEMENT" ADD CONSTRAINT "PK_INCOMESTATEMENT" PRIMARY KEY (
   "NO"
);






---------------------------------------------------
--------------------- 코멘트 -----------------------
---------------------------------------------------


COMMENT ON COLUMN "EMPLOYEE"."NO" IS '사번';

COMMENT ON COLUMN "EMPLOYEE"."PROFILE_IMAGE" IS '프로필사진';

COMMENT ON COLUMN "EMPLOYEE"."PWD" IS '패스워드';

COMMENT ON COLUMN "EMPLOYEE"."NAME" IS '직원명';

COMMENT ON COLUMN "EMPLOYEE"."BIRTH" IS '생년월일';

COMMENT ON COLUMN "EMPLOYEE"."GENDER" IS '성별';

COMMENT ON COLUMN "EMPLOYEE"."EMAIL" IS '이메일';

COMMENT ON COLUMN "EMPLOYEE"."PHONE" IS '전화번호';

COMMENT ON COLUMN "EMPLOYEE"."EMERGENCY_PHONE" IS '비상연락처';

COMMENT ON COLUMN "EMPLOYEE"."ADDRESS" IS '주소';

COMMENT ON COLUMN "EMPLOYEE"."DEPT_CODE" IS '부서코드';

COMMENT ON COLUMN "EMPLOYEE"."POSITION_CODE" IS '직급코드';

COMMENT ON COLUMN "EMPLOYEE"."SALARY" IS '연봉';

COMMENT ON COLUMN "EMPLOYEE"."BANK_CODE" IS '은행코드';

COMMENT ON COLUMN "EMPLOYEE"."ACCOUNT_NO" IS '계좌번호';

COMMENT ON COLUMN "EMPLOYEE"."TOTAL_VACATION_DAYS" IS '총휴가일수';

COMMENT ON COLUMN "EMPLOYEE"."STATUS_CODE" IS '재직상태코드';

COMMENT ON COLUMN "EMPLOYEE"."ENTER_DATE" IS '입사일';

COMMENT ON COLUMN "EMPLOYEE"."OUT_DATE" IS '퇴사일';

COMMENT ON COLUMN "EMPLOYEE"."ENROLL_DATE" IS '등록일자';

COMMENT ON COLUMN "EMPLOYEE"."MODIFY_DATE" IS '수정일자';

COMMENT ON COLUMN "EMPLOYEE"."DEL_YN" IS '삭제여부';

COMMENT ON COLUMN "EMP_STATUS"."NO" IS '재직상태코드';

COMMENT ON COLUMN "EMP_STATUS"."NAME" IS '상태명';

COMMENT ON COLUMN "VACATION_LOG"."NO" IS '휴가신청등록순번';

COMMENT ON COLUMN "VACATION_LOG"."EMP_NO" IS '사번';

COMMENT ON COLUMN "VACATION_LOG"."CODE" IS '휴가유형코드';

COMMENT ON COLUMN "VACATION_LOG"."THISDATE" IS '휴가를사용한날짜';

COMMENT ON COLUMN "VACATION_LOG"."REASON" IS '휴가사유';

COMMENT ON COLUMN "VACATION_LOG"."ENROLL_DATE" IS '등록일자';

COMMENT ON COLUMN "VACATION_LOG"."MODIFY_DATE" IS '수정일자';

COMMENT ON COLUMN "VACATION_LOG"."DEL_YN" IS '삭제여부';

COMMENT ON COLUMN "DEPARTMENT"."NO" IS '부서코드';

COMMENT ON COLUMN "DEPARTMENT"."NAME" IS '부서명';

COMMENT ON COLUMN "SALARY"."NO" IS 'NO';

COMMENT ON COLUMN "SALARY"."EMP_NO" IS '사번';

COMMENT ON COLUMN "SALARY"."PAY_YEARMONTH" IS '지급연월';

COMMENT ON COLUMN "SALARY"."BASIC" IS '기본급';

COMMENT ON COLUMN "SALARY"."MEAL_ALLOWANCE" IS '식대';

COMMENT ON COLUMN "SALARY"."COMMUNICATION_COST" IS '통신비';

COMMENT ON COLUMN "SALARY"."NATIONAL_PENSION" IS '국민연금';

COMMENT ON COLUMN "SALARY"."HEALTH_INSURANCE" IS '건강보험';

COMMENT ON COLUMN "SALARY"."EMPLOYMENT_INSURANCE" IS '고용보험';

COMMENT ON COLUMN "SALARY"."LONGTERM_CARE_INSURANCE" IS '장기요양보험료';

COMMENT ON COLUMN "SALARY"."INCOME_TAX" IS '소득세';

COMMENT ON COLUMN "SALARY"."LOCAL_TAXES" IS '지방소득세';

COMMENT ON COLUMN "POSITION"."NO" IS '직급코드';

COMMENT ON COLUMN "POSITION"."NAME" IS '직급명';

COMMENT ON COLUMN "PRODUCT_REGISTRATION"."NO" IS '상품NO';

COMMENT ON COLUMN "PRODUCT_REGISTRATION"."ITEM_CODE" IS '상품코드';

COMMENT ON COLUMN "PRODUCT_REGISTRATION"."NAME" IS '상품명';

COMMENT ON COLUMN "PRODUCT_REGISTRATION"."SERIAL_NUMBER" IS '상품일련번호';

COMMENT ON COLUMN "PRODUCT_REGISTRATION"."PRICE" IS '가격';

COMMENT ON COLUMN "PRODUCT_REGISTRATION"."WARRANTY_PERIOD" IS '무상보증기간';

COMMENT ON COLUMN "PRODUCT_REGISTRATION"."RECEIVED_DATE" IS '입고일';

COMMENT ON COLUMN "PRODUCT_REGISTRATION"."FACTORY_NAME" IS '생산공정이름';

COMMENT ON COLUMN "PRODUCT_REGISTRATION"."FACTORY_LOCATION" IS '생산공정위치';

COMMENT ON COLUMN "PRODUCT_REGISTRATION"."ENROLL_DATE" IS '등록일자';

COMMENT ON COLUMN "PRODUCT_REGISTRATION"."MODIFY_DATE" IS '수정일자';

COMMENT ON COLUMN "PRODUCT_REGISTRATION"."DEL_YN" IS '삭제여부';

COMMENT ON COLUMN "INSPECTION_HISTORY"."NO" IS 'NO';

COMMENT ON COLUMN "INSPECTION_HISTORY"."PRODUCT_NO" IS '상품NO';

COMMENT ON COLUMN "INSPECTION_HISTORY"."INSPECTION_CODE" IS '검사유형코드';

COMMENT ON COLUMN "INSPECTION_HISTORY"."TYPE" IS '검사방식';

COMMENT ON COLUMN "INSPECTION_HISTORY"."SUCCESS_YN" IS '합격여부';

COMMENT ON COLUMN "INSPECTION_HISTORY"."STATUS_CODE" IS '진행상태코드';

COMMENT ON COLUMN "INSPECTION_HISTORY"."ENROLL_DATE" IS '등록일자';

COMMENT ON COLUMN "INSPECTION_HISTORY"."MODIFY_DATE" IS '수정일자';

COMMENT ON COLUMN "INSPECTION_HISTORY"."DEL_YN" IS '삭제여부';

COMMENT ON COLUMN "DEFECTIVE_CODE"."NO" IS '불량유형코드';

COMMENT ON COLUMN "DEFECTIVE_CODE"."NAME" IS '불량유형명';

COMMENT ON COLUMN "VACATION_TYPE"."NO" IS '휴가유형코드';

COMMENT ON COLUMN "VACATION_TYPE"."NAME" IS '휴가유형명';

COMMENT ON COLUMN "DEFECTIVE_PRODUCT"."NO" IS '불량상품등록순번NO';

COMMENT ON COLUMN "DEFECTIVE_PRODUCT"."P_NO" IS '상품NO';

COMMENT ON COLUMN "DEFECTIVE_PRODUCT"."DEFECTIVE_CODE" IS '불량유형코드';

COMMENT ON COLUMN "DEFECTIVE_PRODUCT"."DESCRIPTION" IS '불량내용';

COMMENT ON COLUMN "DEFECTIVE_PRODUCT"."ENROLL_DATE" IS '등록일자';

COMMENT ON COLUMN "DEFECTIVE_PRODUCT"."MODIFY_DATE" IS '수정일자';

COMMENT ON COLUMN "DEFECTIVE_PRODUCT"."DEL_YN" IS '삭제여부';

COMMENT ON COLUMN "INSPECTION_STATUS"."NO" IS '품질검사상태코드';

COMMENT ON COLUMN "INSPECTION_STATUS"."NAME" IS '품질검사상태명';

COMMENT ON COLUMN "AS_REQUEST"."NO" IS 'AS요청등록순번';

COMMENT ON COLUMN "AS_REQUEST"."P_NO" IS '상품NO';

COMMENT ON COLUMN "AS_REQUEST"."CUSTOMER_NAME" IS '고객명';

COMMENT ON COLUMN "AS_REQUEST"."CUSTOMER_ADRESS" IS '고객주소';

COMMENT ON COLUMN "AS_REQUEST"."CUSTOMER_PHONE" IS '고객핸드폰번호';

COMMENT ON COLUMN "AS_REQUEST"."PURCHASE_DATE" IS '상품구매일';

COMMENT ON COLUMN "AS_REQUEST"."WARRANTY_YN" IS 'AS무상가능여부';

COMMENT ON COLUMN "AS_REQUEST"."ISSUE_TITLE" IS 'AS요청제목';

COMMENT ON COLUMN "AS_REQUEST"."ISSUE_DESCRIPTION" IS 'AS요청내용(증상)';

COMMENT ON COLUMN "AS_REQUEST"."PREFERRED_SERVICE_DATE" IS 'AS희망날짜';

COMMENT ON COLUMN "AS_REQUEST"."STATUS_CODE" IS 'AS진행상태코드';

COMMENT ON COLUMN "AS_REQUEST"."ENROLL_DATE" IS '등록일자';

COMMENT ON COLUMN "AS_REQUEST"."MODIFY_DATE" IS '수정일자';

COMMENT ON COLUMN "AS_REQUEST"."DEL_YN" IS '삭제여부';

COMMENT ON COLUMN "OVERTIME"."NO" IS 'NO';

COMMENT ON COLUMN "OVERTIME"."EMP_NO" IS '사번';

COMMENT ON COLUMN "OVERTIME"."THISDATE" IS '일자';

COMMENT ON COLUMN "OVERTIME"."TYPE" IS '초과근무구분';

COMMENT ON COLUMN "OVERTIME"."WORK_HOUR" IS '초과근무시간';

COMMENT ON COLUMN "INSPECTION_TYPE"."NO" IS '검사유형코드';

COMMENT ON COLUMN "INSPECTION_TYPE"."NAME" IS '검사유형명';

COMMENT ON COLUMN "FAULT_CODE"."NO" IS '고장코드';

COMMENT ON COLUMN "FAULT_CODE"."NAME" IS '고장명';

COMMENT ON COLUMN "PARTNER"."NO" IS '거래처코드';

COMMENT ON COLUMN "PARTNER"."BUSINESS_CODE" IS '업종코드';

COMMENT ON COLUMN "PARTNER"."NAME" IS '상호명';

COMMENT ON COLUMN "PARTNER"."BIZ_REGIST_NO" IS '사업자등록번호';

COMMENT ON COLUMN "PARTNER"."CEO_NAME" IS '대표자명';

COMMENT ON COLUMN "PARTNER"."ADDRESS" IS '주소';

COMMENT ON COLUMN "PARTNER"."DEL_YN" IS '삭제여부';

COMMENT ON COLUMN "SALE"."NO" IS '매출등록순번';

COMMENT ON COLUMN "SALE"."PARTNER_CODE" IS '거래처코드';

COMMENT ON COLUMN "SALE"."TRANS_CODE" IS '거래항목코드';

COMMENT ON COLUMN "SALE"."ACCOUNT_CODE" IS '계좌코드';

COMMENT ON COLUMN "SALE"."TRANS_DATE" IS '거래일자';

COMMENT ON COLUMN "SALE"."SUPPLY_AMOUNT" IS '공급가액';

COMMENT ON COLUMN "SALE"."TAX_AMOUNT" IS '부가세';

COMMENT ON COLUMN "SALE"."ATTACHMENT" IS '증빙사진';

COMMENT ON COLUMN "SALE"."COMMENTS" IS '비고';

COMMENT ON COLUMN "SALE"."ENROLL_DATE" IS '등록일자';

COMMENT ON COLUMN "SALE"."MODIFY_DATE" IS '수정일자';

COMMENT ON COLUMN "SALE"."DEL_YN" IS '삭제여부';

COMMENT ON COLUMN "EXPENSE"."NO" IS '경비등록순번';

COMMENT ON COLUMN "EXPENSE"."PARTNER_CODE" IS '거래처코드';

COMMENT ON COLUMN "EXPENSE"."TRANS_CODE" IS '거래항목코드';

COMMENT ON COLUMN "EXPENSE"."ACCOUNT_CODE" IS '계좌코드';

COMMENT ON COLUMN "EXPENSE"."TRANS_DATE" IS '거래일자';

COMMENT ON COLUMN "EXPENSE"."SUPPLY_AMOUNT" IS '공급가액';

COMMENT ON COLUMN "EXPENSE"."TAX_AMOUNT" IS '부가세';

COMMENT ON COLUMN "EXPENSE"."ATTACHMENT" IS '증빙사진';

COMMENT ON COLUMN "EXPENSE"."COMMENTS" IS '비고';

COMMENT ON COLUMN "EXPENSE"."ENROLL_DATE" IS '등록일자';

COMMENT ON COLUMN "EXPENSE"."MODIFY_DATE" IS '수정일자';

COMMENT ON COLUMN "EXPENSE"."DEL_YN" IS '삭제여부';

COMMENT ON COLUMN "BALANCESHEET"."NO" IS 'NO';

COMMENT ON COLUMN "BALANCESHEET"."YEAR" IS '연도';

COMMENT ON COLUMN "BALANCESHEET"."DEPOSIT" IS '보통예금';

COMMENT ON COLUMN "BALANCESHEET"."PREPAID _TAX" IS '부가세대급금';

COMMENT ON COLUMN "BALANCESHEET"."MERCHADISE" IS '상품';

COMMENT ON COLUMN "BALANCESHEET"."RAW_MATERIAL" IS '원재료';

COMMENT ON COLUMN "BALANCESHEET"."WITHHOLDINGS" IS '예수금';

COMMENT ON COLUMN "BALANCESHEET"."WITHHELD_TAX" IS '부가세예수금';

COMMENT ON COLUMN "BALANCESHEET"."CAPITAL_STOCK" IS '자본금';

COMMENT ON COLUMN "AS_WORK"."NO" IS 'AS작업NO';

COMMENT ON COLUMN "AS_WORK"."AS_NO" IS 'AS요청등록순번';

COMMENT ON COLUMN "AS_WORK"."FAULT_CODE" IS '고장코드';

COMMENT ON COLUMN "AS_WORK"."EMP_NO" IS '사번';

COMMENT ON COLUMN "AS_WORK"."REPAIR_DATE" IS '수리일자';

COMMENT ON COLUMN "AS_WORK"."REPAIR_DETALIS" IS '수리내용';

COMMENT ON COLUMN "AS_WORK"."ENROLL_DATE" IS '등록일자';

COMMENT ON COLUMN "AS_WORK"."MODIFY_DATE" IS '수정일자';

COMMENT ON COLUMN "AS_WORK"."DEL_YN" IS '삭제여부';

COMMENT ON COLUMN "ACCOUNT"."NO" IS 'NO';

COMMENT ON COLUMN "ACCOUNT"."BANK_CODE" IS '은행코드';

COMMENT ON COLUMN "ACCOUNT"."ACCOUNT_NAME" IS '계좌명';

COMMENT ON COLUMN "ACCOUNT"."ACCOUNT_NO" IS '계좌번호';

COMMENT ON COLUMN "TRANS_ITEM"."NO" IS '거래항목코드';

COMMENT ON COLUMN "TRANS_ITEM"."TYPE" IS '거래항목구분';

COMMENT ON COLUMN "TRANS_ITEM"."NAME" IS '거래항목명';

COMMENT ON COLUMN "PURCHASE"."NO" IS '매입등록순번';

COMMENT ON COLUMN "PURCHASE"."PARTNER_CODE" IS '거래처코드';

COMMENT ON COLUMN "PURCHASE"."TRANS_CODE" IS '거래항목코드';

COMMENT ON COLUMN "PURCHASE"."ACCOUNT_CODE" IS '계좌코드';

COMMENT ON COLUMN "PURCHASE"."TRANS_DATE" IS '거래일자';

COMMENT ON COLUMN "PURCHASE"."SUPPLY_AMOUNT" IS '공급가액';

COMMENT ON COLUMN "PURCHASE"."TAX_AMOUNT" IS '부가세';

COMMENT ON COLUMN "PURCHASE"."ATTACHMENT" IS '증빙사진';

COMMENT ON COLUMN "PURCHASE"."COMMENTS" IS '비고';

COMMENT ON COLUMN "PURCHASE"."ENROLL_DATE" IS '등록일자';

COMMENT ON COLUMN "PURCHASE"."MODIFY_DATE" IS '수정일자';

COMMENT ON COLUMN "PURCHASE"."DEL_YN" IS '삭제여부';

COMMENT ON COLUMN "PRODUCT_INQUIRY"."NO" IS '상품코드';

COMMENT ON COLUMN "PRODUCT_INQUIRY"."QUANTITY" IS '수량';

COMMENT ON COLUMN "PRODUCT_INQUIRY"."ITEM_NAME" IS '상품명';

COMMENT ON COLUMN "PRODUCT_INQUIRY"."ITEM_IMAGE" IS '상품사진';

COMMENT ON COLUMN "AS_ENGINEERS"."NO" IS '사번';

COMMENT ON COLUMN "AS_ENGINEERS"."AREA" IS '담당지역';

COMMENT ON COLUMN "DEFECTIVE_IMAGES"."NO" IS '사진NO';

COMMENT ON COLUMN "DEFECTIVE_IMAGES"."REFNO" IS '불량상품등록순번NO';

COMMENT ON COLUMN "DEFECTIVE_IMAGES"."PATH" IS '사진경로';

COMMENT ON COLUMN "ATTENDANCE"."NO" IS 'NO';

COMMENT ON COLUMN "ATTENDANCE"."EMP_NO" IS '사번';

COMMENT ON COLUMN "ATTENDANCE"."CI_TIME" IS '출근시간';

COMMENT ON COLUMN "ATTENDANCE"."CO_TIME" IS '퇴근시간';

COMMENT ON COLUMN "ATTENDANCE"."DEL_YN" IS '삭제여부';

COMMENT ON COLUMN "SALARY_PAYMENT"."NO" IS '급여지급등록순번';

COMMENT ON COLUMN "SALARY_PAYMENT"."TRANS_CODE" IS '거래항목코드';

COMMENT ON COLUMN "SALARY_PAYMENT"."ACCOUNT_CODE" IS '계좌코드';

COMMENT ON COLUMN "SALARY_PAYMENT"."EMP_NO" IS '사번';

COMMENT ON COLUMN "SALARY_PAYMENT"."PAYMENT_DATE" IS '지급일자';

COMMENT ON COLUMN "SALARY_PAYMENT"."PAYMENT_YEAR_MONTH" IS '지급대상근무연월';

COMMENT ON COLUMN "SALARY_PAYMENT"."BASIC" IS '기본급';

COMMENT ON COLUMN "SALARY_PAYMENT"."MEAL_ALLOWANCE" IS '식대';

COMMENT ON COLUMN "SALARY_PAYMENT"."COMMUNICATION_COST" IS '통신비';

COMMENT ON COLUMN "SALARY_PAYMENT"."NIGHT_PAY" IS '야간수당';

COMMENT ON COLUMN "SALARY_PAYMENT"."WEEKEND_PAY" IS '주말근무수당';

COMMENT ON COLUMN "SALARY_PAYMENT"."EXTRA_PAY" IS '추가수당';

COMMENT ON COLUMN "SALARY_PAYMENT"."TOTAL_PAY" IS '지급총액';

COMMENT ON COLUMN "SALARY_PAYMENT"."NATIONAL_PENSION" IS '국민연금';

COMMENT ON COLUMN "SALARY_PAYMENT"."HEALTH_INSURANCE" IS '건강보험';

COMMENT ON COLUMN "SALARY_PAYMENT"."EMPLOYMENT_INSURANCE" IS '고용보험';

COMMENT ON COLUMN "SALARY_PAYMENT"."LONGTERM_CARE_INSURANCE" IS '장기요양보험료';

COMMENT ON COLUMN "SALARY_PAYMENT"."INCOME_TAX" IS '소득세';

COMMENT ON COLUMN "SALARY_PAYMENT"."LOCAL_TAXES" IS '지방소득세';

COMMENT ON COLUMN "SALARY_PAYMENT"."EXTRA_DEDUCTION" IS '추가공제';

COMMENT ON COLUMN "SALARY_PAYMENT"."TOTAL_DEDUCTION" IS '공제총액';

COMMENT ON COLUMN "SALARY_PAYMENT"."NET_PAY" IS '실지급액';

COMMENT ON COLUMN "SALARY_PAYMENT"."ATTACHMENT" IS '증빙사진';

COMMENT ON COLUMN "SALARY_PAYMENT"."COMMENTS" IS '비고';

COMMENT ON COLUMN "SALARY_PAYMENT"."ENROLL_DATE" IS '등록일자';

COMMENT ON COLUMN "SALARY_PAYMENT"."MODIFY_DATE" IS '수정일자';

COMMENT ON COLUMN "SALARY_PAYMENT"."DEL_YN" IS '삭제여부';

COMMENT ON COLUMN "BANK"."NO" IS '은행코드';

COMMENT ON COLUMN "BANK"."NAME" IS '은행명';

COMMENT ON COLUMN "AS_STATUS"."NO" IS 'AS진행상태코드';

COMMENT ON COLUMN "AS_STATUS"."NAME" IS 'AS진행상태명';

COMMENT ON COLUMN "ADMIN"."NO" IS '관리자번호';

COMMENT ON COLUMN "ADMIN"."EMAIL" IS '이메일';

COMMENT ON COLUMN "ADMIN"."PWD" IS '패스워드';

COMMENT ON COLUMN "BUSINESS_TYPE"."NO" IS 'NO';

COMMENT ON COLUMN "BUSINESS_TYPE"."BIZ_TYPE" IS '업태';

COMMENT ON COLUMN "BUSINESS_TYPE"."BIZ_CATEGORY" IS '업종';

COMMENT ON COLUMN "EXPENSE_ATTACHMENT"."NO" IS '사진NO';

COMMENT ON COLUMN "EXPENSE_ATTACHMENT"."EXPENSE_NO" IS '경비등록순번';

COMMENT ON COLUMN "EXPENSE_ATTACHMENT"."PATH" IS '사진경로';

COMMENT ON COLUMN "SALE_ATTACHMENT"."NO" IS '사진NO';

COMMENT ON COLUMN "SALE_ATTACHMENT"."SALE_NO" IS '매출등록순번';

COMMENT ON COLUMN "SALE_ATTACHMENT"."PATH" IS '사진경로';

COMMENT ON COLUMN "PURCHASE_ATTACHMENT"."NO" IS '사진NO';

COMMENT ON COLUMN "PURCHASE_ATTACHMENT"."PURCHASE_NO" IS '매입등록순번';

COMMENT ON COLUMN "PURCHASE_ATTACHMENT"."PATH" IS '사진경로';

COMMENT ON COLUMN "SALARY_ATTACHMENT"."NO" IS '사진NO';

COMMENT ON COLUMN "SALARY_ATTACHMENT"."PAYMENT_NO" IS '급여지급등록순번';

COMMENT ON COLUMN "SALARY_ATTACHMENT"."PATH" IS '사진경로';

COMMENT ON COLUMN "INCOMESTATEMENT"."NO" IS 'NO';

COMMENT ON COLUMN "INCOMESTATEMENT"."YEAR" IS '연도';

COMMENT ON COLUMN "INCOMESTATEMENT"."SALES_MERCHANDISE" IS '상품매출';

COMMENT ON COLUMN "INCOMESTATEMENT"."SALES_GOODS" IS '제품매출';

COMMENT ON COLUMN "INCOMESTATEMENT"."SALARIES_EXPENSE" IS '직원급여';

COMMENT ON COLUMN "INCOMESTATEMENT"."TRAVEL_EXPENSE" IS '여비교통비';

COMMENT ON COLUMN "INCOMESTATEMENT"."TAXES_DUES" IS '세금과공과';

COMMENT ON COLUMN "INCOMESTATEMENT"."SUPPLIES_EXPENSE" IS '소모품비';

COMMENT ON COLUMN "INCOMESTATEMENT"."ADVERTISING" IS '광고선전비';


---------------------------------------------------
--------------------- 데이터 -----------------------
---------------------------------------------------
INSERT INTO EMPLOYEE(
    NO,PROFILE_IMAGE,PWD, NAME,BIRTH,GENDER,EMAIL,PHONE, EMERGENCY_PHONE, ADDRESS, DEPT_CODE, POSITION_CODE, SALARY,BANK_CODE, ACCOUNT_NO,  TOTAL_VACATION_DAYS, STATUS_CODE,  ENTER_DATE,OUT_DATE
    )VALUES(
    6,'1','1234','1','980601','F','kims8479@naver.com','01077518478','155-522','경기도 용인시 처인구 원삼면 가재월리555-114번지',1,1,3400000,1,'1111111',1,1,'20190815','11111111'
    );
    COMMIT;
    rollback;

---------------------------------------------------
--------------------- 외래키FK -----------------------
---------------------------------------------------

--ALTER TABLE "EMPLOYEE" ADD CONSTRAINT "FK_DEPARTMENT_TO_EMPLOYEE_1" FOREIGN KEY (
--   "DEPT_CODE"
--)
--REFERENCES "DEPARTMENT" (
--   "NO"
--);
--
--ALTER TABLE "EMPLOYEE" ADD CONSTRAINT "FK_POSITION_TO_EMPLOYEE_1" FOREIGN KEY (
--   "POSITION_CODE"
--)
--REFERENCES "POSITION" (
--   "NO"
--);
--
--ALTER TABLE "EMPLOYEE" ADD CONSTRAINT "FK_BANK_TO_EMPLOYEE_1" FOREIGN KEY (
--   "BANK_CODE"
--)
--REFERENCES "BANK" (
--   "NO"
--);
--
--ALTER TABLE "EMPLOYEE" ADD CONSTRAINT "FK_EMP_STATUS_TO_EMPLOYEE_1" FOREIGN KEY (
--   "STATUS_CODE"
--)
--REFERENCES "EMP_STATUS" (
--   "NO"
--);
--
--ALTER TABLE "VACATION_LOG" ADD CONSTRAINT "FK_EMPLOYEE_TO_VACATION_LOG_1" FOREIGN KEY (
--   "EMP_NO"
--)
--REFERENCES "EMPLOYEE" (
--   "NO"
--);
--
--ALTER TABLE "VACATION_LOG" ADD CONSTRAINT "FK_VACATION_TYPE_TO_VACATION_LOG_1" FOREIGN KEY (
--   "CODE"
--)
--REFERENCES "VACATION_TYPE" (
--   "NO"
--);
--
--ALTER TABLE "SALARY" ADD CONSTRAINT "FK_EMPLOYEE_TO_SALARY_1" FOREIGN KEY (
--   "EMP_NO"
--)
--REFERENCES "EMPLOYEE" (
--   "NO"
--);
--
--ALTER TABLE "PRODUCT_REGISTRATION" ADD CONSTRAINT "FK_PRODUCT_INQUIRY_TO_PRODUCT_REGISTRATION_1" FOREIGN KEY (
--   "ITEM_CODE"
--)
--REFERENCES "PRODUCT_INQUIRY" (
--   "NO"
--);
--
--ALTER TABLE "INSPECTION_HISTORY" ADD CONSTRAINT "FK_PRODUCT_REGISTRATION_TO_INSPECTION_HISTORY_1" FOREIGN KEY (
--   "PRODUCT_NO"
--)
--REFERENCES "PRODUCT_REGISTRATION" (
--   "NO"
--);
--
--ALTER TABLE "INSPECTION_HISTORY" ADD CONSTRAINT "FK_INSPECTION_TYPE_TO_INSPECTION_HISTORY_1" FOREIGN KEY (
--   "INSPECTION_CODE"
--)
--REFERENCES "INSPECTION_TYPE" (
--   "NO"
--);
--
--ALTER TABLE "INSPECTION_HISTORY" ADD CONSTRAINT "FK_INSPECTION_STATUS_TO_INSPECTION_HISTORY_1" FOREIGN KEY (
--   "STATUS_CODE"
--)
--REFERENCES "INSPECTION_STATUS" (
--   "NO"
--);
--
--ALTER TABLE "DEFECTIVE_PRODUCT" ADD CONSTRAINT "FK_PRODUCT_REGISTRATION_TO_DEFECTIVE_PRODUCT_1" FOREIGN KEY (
--   "P_NO"
--)
--REFERENCES "PRODUCT_REGISTRATION" (
--   "NO"
--);
--
--ALTER TABLE "DEFECTIVE_PRODUCT" ADD CONSTRAINT "FK_DEFECTIVE_CODE_TO_DEFECTIVE_PRODUCT_1" FOREIGN KEY (
--   "DEFECTIVE_CODE"
--)
--REFERENCES "DEFECTIVE_CODE" (
--   "NO"
--);
--
--ALTER TABLE "AS_REQUEST" ADD CONSTRAINT "FK_PRODUCT_REGISTRATION_TO_AS_REQUEST_1" FOREIGN KEY (
--   "P_NO"
--)
--REFERENCES "PRODUCT_REGISTRATION" (
--   "NO"
--);
--
--ALTER TABLE "AS_REQUEST" ADD CONSTRAINT "FK_AS_STATUS_TO_AS_REQUEST_1" FOREIGN KEY (
--   "STATUS_CODE"
--)
--REFERENCES "AS_STATUS" (
--   "NO"
--);
--
--ALTER TABLE "OVERTIME" ADD CONSTRAINT "FK_EMPLOYEE_TO_OVERTIME_1" FOREIGN KEY (
--   "EMP_NO"
--)
--REFERENCES "EMPLOYEE" (
--   "NO"
--);
--
--ALTER TABLE "PARTNER" ADD CONSTRAINT "FK_BUSINESS_TYPE_TO_PARTNER_1" FOREIGN KEY (
--   "BUSINESS_CODE"
--)
--REFERENCES "BUSINESS_TYPE" (
--   "NO"
--);
--
--ALTER TABLE "SALE" ADD CONSTRAINT "FK_PARTNER_TO_SALE_1" FOREIGN KEY (
--   "PARTNER_CODE"
--)
--REFERENCES "PARTNER" (
--   "NO"
--);
--
--ALTER TABLE "SALE" ADD CONSTRAINT "FK_TRANS_ITEM_TO_SALE_1" FOREIGN KEY (
--   "TRANS_CODE"
--)
--REFERENCES "TRANS_ITEM" (
--   "NO"
--);
--
--ALTER TABLE "SALE" ADD CONSTRAINT "FK_ACCOUNT_TO_SALE_1" FOREIGN KEY (
--   "ACCOUNT_CODE"
--)
--REFERENCES "ACCOUNT" (
--   "NO"
--);
--
--ALTER TABLE "EXPENSE" ADD CONSTRAINT "FK_PARTNER_TO_EXPENSE_1" FOREIGN KEY (
--   "PARTNER_CODE"
--)
--REFERENCES "PARTNER" (
--   "NO"
--);
--
--ALTER TABLE "EXPENSE" ADD CONSTRAINT "FK_TRANS_ITEM_TO_EXPENSE_1" FOREIGN KEY (
--   "TRANS_CODE"
--)
--REFERENCES "TRANS_ITEM" (
--   "NO"
--);
--
--ALTER TABLE "EXPENSE" ADD CONSTRAINT "FK_ACCOUNT_TO_EXPENSE_1" FOREIGN KEY (
--   "ACCOUNT_CODE"
--)
--REFERENCES "ACCOUNT" (
--   "NO"
--);
--
--ALTER TABLE "AS_WORK" ADD CONSTRAINT "FK_AS_REQUEST_TO_AS_WORK_1" FOREIGN KEY (
--   "AS_NO"
--)
--REFERENCES "AS_REQUEST" (
--   "NO"
--);
--
--ALTER TABLE "AS_WORK" ADD CONSTRAINT "FK_FAULT_CODE_TO_AS_WORK_1" FOREIGN KEY (
--   "FAULT_CODE"
--)
--REFERENCES "FAULT_CODE" (
--   "NO"
--);
--
--ALTER TABLE "AS_WORK" ADD CONSTRAINT "FK_AS_ENGINEERS_TO_AS_WORK_1" FOREIGN KEY (
--   "EMP_NO"
--)
--REFERENCES "AS_ENGINEERS" (
--   "NO"
--);
--
--ALTER TABLE "ACCOUNT" ADD CONSTRAINT "FK_BANK_TO_ACCOUNT_1" FOREIGN KEY (
--   "BANK_CODE"
--)
--REFERENCES "BANK" (
--   "NO"
--);
--
--ALTER TABLE "PURCHASE" ADD CONSTRAINT "FK_PARTNER_TO_PURCHASE_1" FOREIGN KEY (
--   "PARTNER_CODE"
--)
--REFERENCES "PARTNER" (
--   "NO"
--);
--
--ALTER TABLE "PURCHASE" ADD CONSTRAINT "FK_TRANS_ITEM_TO_PURCHASE_1" FOREIGN KEY (
--   "TRANS_CODE"
--)
--REFERENCES "TRANS_ITEM" (
--   "NO"
--);
--
--ALTER TABLE "PURCHASE" ADD CONSTRAINT "FK_ACCOUNT_TO_PURCHASE_1" FOREIGN KEY (
--   "ACCOUNT_CODE"
--)
--REFERENCES "ACCOUNT" (
--   "NO"
--);
--
--ALTER TABLE "AS_ENGINEERS" ADD CONSTRAINT "FK_EMPLOYEE_TO_AS_ENGINEERS_1" FOREIGN KEY (
--   "NO"
--)
--REFERENCES "EMPLOYEE" (
--   "NO"
--);
--
--ALTER TABLE "DEFECTIVE_IMAGES" ADD CONSTRAINT "FK_DEFECTIVE_PRODUCT_TO_DEFECTIVE_IMAGES_1" FOREIGN KEY (
--   "REFNO"
--)
--REFERENCES "DEFECTIVE_PRODUCT" (
--   "NO"
--);
--
--ALTER TABLE "ATTENDANCE" ADD CONSTRAINT "FK_EMPLOYEE_TO_ATTENDANCE_1" FOREIGN KEY (
--   "EMP_NO"
--)
--REFERENCES "EMPLOYEE" (
--   "NO"
--);
--
--ALTER TABLE "SALARY_PAYMENT" ADD CONSTRAINT "FK_TRANS_ITEM_TO_SALARY_PAYMENT_1" FOREIGN KEY (
--   "TRANS_CODE"
--)
--REFERENCES "TRANS_ITEM" (
--   "NO"
--);
--
--ALTER TABLE "SALARY_PAYMENT" ADD CONSTRAINT "FK_ACCOUNT_TO_SALARY_PAYMENT_1" FOREIGN KEY (
--   "ACCOUNT_CODE"
--)
--REFERENCES "ACCOUNT" (
--   "NO"
--);
--
--ALTER TABLE "SALARY_PAYMENT" ADD CONSTRAINT "FK_EMPLOYEE_TO_SALARY_PAYMENT_1" FOREIGN KEY (
--   "EMP_NO"
--)
--REFERENCES "EMPLOYEE" (
--   "NO"
--);
--
--ALTER TABLE "EXPENSE_ATTACHMENT" ADD CONSTRAINT "FK_EXPENSE_TO_EXPENSE_ATTACHMENT_1" FOREIGN KEY (
--   "EXPENSE_NO"
--)
--REFERENCES "EXPENSE" (
--   "NO"
--);
--
--ALTER TABLE "SALE_ATTACHMENT" ADD CONSTRAINT "FK_SALE_TO_SALE_ATTACHMENT_1" FOREIGN KEY (
--   "SALE_NO"
--)
--REFERENCES "SALE" (
--   "NO"
--);
--
--ALTER TABLE "PURCHASE_ATTACHMENT" ADD CONSTRAINT "FK_PURCHASE_TO_PURCHASE_ATTACHMENT_1" FOREIGN KEY (
--   "PURCHASE_NO"
--)
--REFERENCES "PURCHASE" (
--   "NO"
--);
--
--ALTER TABLE "SALARY_ATTACHMENT" ADD CONSTRAINT "FK_SALARY_PAYMENT_TO_SALARY_ATTACHMENT_1" FOREIGN KEY (
--   "PAYMENT_NO"
--)
--REFERENCES "SALARY_PAYMENT" (
--   "NO"
--);
--
------------------------------------------------------
--------------------DML-------------------------------
------------------------------------------------------
SELECT * FROM BOARD;
