------------------------------- DIET -------------------------------

-- DIET, MEAL
INSERT INTO DIET
(
    NO
    , MEMBER_NO
    , MEAL_CODE
    , DIET_DAY
    , MEMO
    , IMAGE
)
VALUES
(
    SEQ_DIET.NEXTVAL
    , #{memberNo}
    , #{mealCode}
    , #{dietDay}
    , #{memo}
    , #{image}
)
;

INSERT INTO MEAL_LOG
(
    NO
    , DIET_NO
    , NAME
    , UNIT
    , AMOUNT
    , KCAL
) 
VALUES 
(
    SEQ_MEAL_LOG.NEXTVAL
    , SEQ_DIET.CURRVAL
    , #{label}
    , #{unit}
    , #{amount}
    , #{kcal}
)
;

SELECT
    NO
    , MEMBER_NO
    , MEAL_CODE
    , DIET_DAY, MEMO
    , IMAGE
    , ENROLL_DATE
    , MODIFY_DATE
    , DEL_YN
FROM DIET
WHERE MEMBER_NO = #{memberNo}
AND DIET_DAY = #{dietDay}
AND DEL_YN = 'N'
;

SELECT NVL(SUM(KCAL), 0) AS SUM_KCAL
FROM MEAL_LOG
WHERE DIET_NO = #{no}
;
            
SELECT 
    NO
    , DIET_NO
    , NAME AS LABEL
    , UNIT
    , AMOUNT
    , KCAL
FROM MEAL_LOG
WHERE DIET_NO = #{no}
;

UPDATE DIET
SET MEMO = #{memo}
    , IMAGE = #{image}
    , MODIFY_DATE = SYSDATE
WHERE NO = #{no}
AND DEL_YN = 'N'
;

DELETE FROM MEAL_LOG
WHERE DIET_NO = #{no}
;

UPDATE DIET
SET DEL_YN = 'Y'
WHERE NO = #{no}
;

SELECT 
    NO
    , NAME AS LABEL
    , UNIT
    , AMOUNT
    , KCAL
FROM FOOD
ORDER BY LABEL 
;

SELECT COUNT(*)
FROM NOTIFICATION_SETTINGS
WHERE
MEMBER_NO = #{userNo}
AND ALL_PUSH = 'Y'
AND DIET_PUSH = 'Y'
;

SELECT COUNT(*)
FROM DIET
WHERE MEMBER_NO = #{userNo}
AND TRUNC(DIET_DAY) = TRUNC(SYSDATE)
AND DEL_YN = 'N'
;


-- WATER
INSERT INTO WATER_LOG 
( 
    NO
    , MEMBER_NO
    , ENROLL_DATE
    , AMOUNT 
) 
VALUES 
(
     SEQ_WATER_LOG.NEXTVAL
     , #{memberNo}
     , #{enrollDate}
     , #{amount}
)
;
            
UPDATE WATER_LOG
SET AMOUNT = #{amount}
WHERE MEMBER_NO = #{memberNo}
AND TRUNC(ENROLL_DATE) = #{enrollDate}
;
            
SELECT AMOUNT
FROM WATER_LOG
WHERE MEMBER_NO = #{memberNo}
AND TRUNC(ENROLL_DATE) = #{enrollDate}
;

SELECT COUNT(*)
FROM WATER_LOG
WHERE MEMBER_NO = #{userNo}
AND TRUNC(ENROLL_DATE) = TRUNC(SYSDATE)
AND EXISTS (
        SELECT 1
        FROM NOTIFICATION_SETTINGS NS
        WHERE NS.MEMBER_NO = #{userNo}
            AND NS.ALL_PUSH = 'Y'
            AND NS.WATER_PUSH = 'Y'
    )
;
    
SELECT COUNT(*)
FROM NOTIFICATION_SETTINGS
WHERE
MEMBER_NO = #{userNo}
AND ALL_PUSH = 'Y'
AND WATER_PUSH = 'Y'
;


-- WEIGHT
INSERT INTO WEIGHT_LOG
(
    NO
    , MEMBER_NO
    , ENROLL_DATE
    , AMOUNT
) 
VALUES 
(
    SEQ_WEIGHT_LOG.NEXTVAL
    , #{memberNo}
    , #{enrollDate}
    , #{amount}
)
;
            
UPDATE WEIGHT_LOG
SET AMOUNT = #{amount}
WHERE MEMBER_NO = #{memberNo}
AND TRUNC(ENROLL_DATE) = #{enrollDate}
;
            
SELECT AMOUNT
FROM WEIGHT_LOG
WHERE MEMBER_NO = #{memberNo}
AND TRUNC(ENROLL_DATE) = #{enrollDate}
;
            
SELECT ENROLL_DATE, AMOUNT
FROM WEIGHT_LOG
WHERE MEMBER_NO = #{memberNo}
ORDER BY ENROLL_DATE
;


-- CALENDAR
SELECT
    DT.ENROLL_DATE AS DIET_DAY
    , DT.MEMBER_NO
    , NVL(WT.AMOUNT, 0) AS WATER_AMOUNT
    , NVL(WG.AMOUNT, 0) AS WEIGHT_AMOUNT
    , NVL(SUM_KCAL, 0) AS SUM_KCAL
FROM
    (SELECT MEMBER_NO, ENROLL_DATE FROM WATER_LOG
    UNION
    SELECT MEMBER_NO, ENROLL_DATE FROM WEIGHT_LOG
    UNION
    SELECT MEMBER_NO, DIET_DAY FROM DIET) DT
LEFT JOIN WATER_LOG WT ON (DT.ENROLL_DATE = WT.ENROLL_DATE AND DT.MEMBER_NO = WT.MEMBER_NO)
LEFT JOIN WEIGHT_LOG WG ON (DT.ENROLL_DATE = WG.ENROLL_DATE AND DT.MEMBER_NO = WG.MEMBER_NO)
LEFT JOIN (
    SELECT D.MEMBER_NO, D.DIET_DAY, SUM(M.KCAL) AS SUM_KCAL
    FROM DIET D
    LEFT JOIN MEAL_LOG M ON D.NO = M.DIET_NO
    WHERE D.DEL_YN = 'N'
    GROUP BY D.MEMBER_NO, D.DIET_DAY
) DIET_SUM ON (DT.ENROLL_DATE = DIET_SUM.DIET_DAY AND DT.MEMBER_NO = DIET_SUM.MEMBER_NO)
WHERE DT.MEMBER_NO = #{memberNo}
ORDER BY DIET_DAY
;


-- REPORT
SELECT ENROLL_DATE, AMOUNT
FROM WATER_LOG
WHERE MEMBER_NO = #{memberNo}
AND TO_CHAR(ENROLL_DATE, 'YYYY-MM') = #{month}
ORDER BY ENROLL_DATE
;

SELECT ENROLL_DATE, AMOUNT
FROM WEIGHT_LOG
WHERE MEMBER_NO = #{memberNo}
AND TO_CHAR(ENROLL_DATE, 'YYYY-MM') = #{month}
ORDER BY ENROLL_DATE
;

SELECT DIET_DAY, SUM(M.KCAL) AS TOTAL_KCAL
FROM DIET D
LEFT JOIN MEAL_LOG M ON (D.NO = M.DIET_NO)
WHERE D.MEMBER_NO = #{memberNo}
AND TO_CHAR(D.DIET_DAY, 'YYYY-MM') = #{month}
AND D.DEL_YN = 'N'
GROUP BY D.MEMBER_NO, D.DIET_DAY
ORDER BY D.DIET_DAY
;

SELECT TO_CHAR(ENROLL_DATE, 'YYYY-MM') AS ENROLL_DATE,  ROUND(AVG(AMOUNT)) AS AMOUNT
FROM WATER_LOG
WHERE MEMBER_NO = #{memberNo}
AND TO_CHAR(ENROLL_DATE, 'YYYY') = #{year}
GROUP BY TO_CHAR(ENROLL_DATE, 'YYYY-MM')
ORDER BY ENROLL_DATE
;

SELECT TO_CHAR(ENROLL_DATE, 'YYYY-MM') AS ENROLL_DATE,  ROUND(AVG(AMOUNT)) AS AMOUNT
FROM WEIGHT_LOG
WHERE MEMBER_NO = #{memberNo}
AND TO_CHAR(ENROLL_DATE, 'YYYY') = #{year}
GROUP BY TO_CHAR(ENROLL_DATE, 'YYYY-MM')
ORDER BY ENROLL_DATE
;

SELECT TO_CHAR(D.DIET_DAY, 'YYYY-MM') AS DIET_DAY, ROUND(SUM(M.KCAL)/COUNT(DISTINCT D.DIET_DAY),0) AS TOTAL_KCAL
FROM DIET D
LEFT JOIN MEAL_LOG M ON (D.NO = M.DIET_NO)
WHERE D.MEMBER_NO = #{memberNo}
AND TO_CHAR(D.DIET_DAY, 'YYYY') = #{year}
AND D.DEL_YN = 'N'
GROUP BY D.MEMBER_NO, TO_CHAR(D.DIET_DAY, 'YYYY-MM')
ORDER BY DIET_DAY
;

SELECT TO_CHAR(ENROLL_DATE, 'YYYY') AS ENROLL_DATE,  ROUND(AVG(AMOUNT)) AS AMOUNT
FROM WATER_LOG
WHERE MEMBER_NO = #{memberNo}
GROUP BY TO_CHAR(ENROLL_DATE, 'YYYY')
ORDER BY ENROLL_DATE
;

SELECT TO_CHAR(ENROLL_DATE, 'YYYY') AS ENROLL_DATE,  ROUND(AVG(AMOUNT)) AS AMOUNT
FROM WEIGHT_LOG
WHERE MEMBER_NO = #{memberNo}
GROUP BY TO_CHAR(ENROLL_DATE, 'YYYY')
ORDER BY ENROLL_DATE
;

SELECT TO_CHAR(D.DIET_DAY, 'YYYY') AS DIET_DAY, ROUND(SUM(M.KCAL)/COUNT(DISTINCT D.DIET_DAY),0) AS TOTAL_KCAL
FROM DIET D
LEFT JOIN MEAL_LOG M ON (D.NO = M.DIET_NO)
WHERE D.MEMBER_NO = #{memberNo}
AND D.DEL_YN = 'N'
GROUP BY D.MEMBER_NO, TO_CHAR(D.DIET_DAY, 'YYYY')
ORDER BY DIET_DAY
;

------------------------------- DASHBOARD -------------------------------
SELECT
NVL((SELECT MAX(SYSTOLE) FROM BLOOD_PRESSURE WHERE MEMBER_NO = #{memberNo} AND ENROLL_DATE BETWEEN #{startDate} AND #{endDate}), 0) AS MAX_BLOOD_PRESSURE, 
NVL((SELECT MIN(SYSTOLE) FROM BLOOD_PRESSURE WHERE MEMBER_NO = #{memberNo} AND ENROLL_DATE BETWEEN #{startDate} AND #{endDate}), 0) AS MIN_BLOOD_PRESSURE,  
NVL((SELECT MAX(SUGAR) FROM BLOOD_SUGAR WHERE MEMBER_NO = #{memberNo} AND ENROLL_DATE BETWEEN #{startDate} AND #{endDate}),0) AS MAX_BLOOD_SUGAR,                                       
NVL((SELECT MIN(SUGAR) FROM BLOOD_SUGAR WHERE MEMBER_NO = #{memberNo} AND ENROLL_DATE BETWEEN #{startDate} AND #{endDate}), 0) AS MIN_BLOOD_SUGAR,          
ROUND(NVL((SELECT AVG(SLEEP_DURATION) FROM SLEEP WHERE MEMBER_NO = #{memberNo} AND RECORD_DATE BETWEEN #{startDate} AND #{endDate}), 0)) AS AVG_SLEEP,            
(SELECT
    ROUND(SUM(
        CONSUMPTION_RATIO *
        (LEAST(TO_DATE(#{endDate}, 'YY/MM/DD'), END_DATE) -
         GREATEST(TO_DATE(#{startDate}, 'YY/MM/DD'), START_DATE) + 1)
    ), 2)
FROM (
    SELECT
        NO, MEMBER_NO, CIGARETTE, START_DATE, END_DATE,
        (END_DATE - START_DATE + 1) AS DAYS_CONSUMED,
        (1 / (END_DATE - START_DATE + 1)) AS CONSUMPTION_RATIO
    FROM RECORD_CIGARETTE
    WHERE MEMBER_NO = #{memberNo}
    AND (START_DATE <= TO_DATE(#{endDate}, 'YY/MM/DD'))
    AND (END_DATE >= TO_DATE(#{startDate}, 'YY/MM/DD'))
)) AS COUNT_CIGARETTE, 
NVL((SELECT SUM((ABV/100)*CC) FROM RECORD_ALC WHERE MEMBER_NO = #{memberNo} AND ENROLL_DATE BETWEEN #{startDate} AND #{endDate}), 0) AS SUM_ALC,             
ROUND(NVL((SELECT AVG(AMOUNT) FROM WEIGHT_LOG WHERE MEMBER_NO = #{memberNo} AND ENROLL_DATE BETWEEN #{startDate} AND #{endDate}), 0),1) AS AVG_WEIGHT,               
ROUND(NVL((SELECT AVG(SUM(KCAL)) FROM DIET D JOIN MEAL_LOG M ON (D.NO = M.DIET_NO) WHERE MEMBER_NO = #{memberNo} AND DIET_DAY BETWEEN #{startDate} AND #{endDate} AND DEL_YN = 'N' GROUP BY DIET_DAY), 0),1) AS AVG_KCAL,
ROUND(NVL((SELECT AVG(AMOUNT) FROM WATER_LOG WHERE MEMBER_NO = #{memberNo} AND ENROLL_DATE BETWEEN #{startDate} AND #{endDate}),0),1) AS AVG_WATER,                 
NVL((SELECT SUM(EX_DURATION) FROM AEROBIC_HISTORY WHERE USER_NO = #{memberNo} AND EX_DATE BETWEEN #{startDate} AND #{endDate}),0) AS SUM_AEROBIC,         
NVL((SELECT COUNT(DISTINCT EX_DATE) FROM ANAEROBIC_HISTORY WHERE USER_NO = #{memberNo} AND EX_DATE BETWEEN #{startDate} AND #{endDate}), 0) AS COUNT_ANAEROBIC,          
ROUND(NVL((SELECT SUM((CAL_CONSUME/60)*EX_DURATION)
FROM AEROBIC_HISTORY H
JOIN AEROBIC A ON (H.EX_NO = A.NO)
WHERE USER_NO = #{memberNo}
AND EX_DATE BETWEEN #{startDate} AND #{endDate}),0)
+
NVL((SELECT SUM(REPS*CAL_CONSUME)
FROM ANAEROBIC_HISTORY H
JOIN ANAEROBIC A ON (H.EX_NO = A.NO)
WHERE USER_NO = #{memberNo} 
AND EX_DATE BETWEEN #{startDate} AND #{endDate}),0),1)
AS SUM_CAL_CONSUME 
FROM DUAL
;

SELECT NO, NAME, VISIBLE_YN
FROM DASHBOARD
WHERE MEMBER_NO = #{memberNo}
ORDER BY NO
;

            UPDATE DASHBOARD
SET VISIBLE_YN = #{visibleYn}
WHERE NO = #{no}
;


------------------------------- USER MAIN -------------------------------
-- BOARD
-- 최근 7일 내 추천수 가장 높은 게시물 3개 보여줌
-- 최근 7일 내 등록된 게시글 없을 시 최근 게시물 3개 보여줌
SELECT * FROM (
SELECT
    B.NO,
    B.CATEGORY_NO,
    C.NAME AS CATEGORY_NAME,
    B.MEMBER_NO,
    M.NICK,
    M.PROFILE,
    B.TITLE,
    B.CONTENT,
    NVL(R.RECOMMEND_COUNT, 0) AS RECOMMEND_COUNT,
    B.ENROLL_DATE
FROM BOARD B
JOIN CATEGORY C ON (B.CATEGORY_NO = C.NO)
JOIN MEMBER M ON (B.MEMBER_NO = M.NO)
LEFT JOIN (
    SELECT BOARD_NO, COUNT(*) AS RECOMMEND_COUNT
    FROM BOARD_RECOMMEND
    GROUP BY BOARD_NO
) R ON B.NO = R.BOARD_NO
WHERE B.DEL_YN = 'N'
AND B.ENROLL_DATE >= SYSDATE - 7
ORDER BY RECOMMEND_COUNT DESC, B.ENROLL_DATE DESC
)
WHERE ROWNUM <= 3

UNION ALL

SELECT * FROM (
    SELECT
        B.NO,
        B.CATEGORY_NO,
        C.NAME AS CATEGORY_NAME,
        B.MEMBER_NO,
        M.NICK,
        M.PROFILE,
        B.TITLE,
        B.CONTENT,
        NVL(R.RECOMMEND_COUNT, 0) AS RECOMMEND_COUNT,
        B.ENROLL_DATE
    FROM BOARD B
    JOIN CATEGORY C ON (B.CATEGORY_NO = C.NO)
    JOIN MEMBER M ON (B.MEMBER_NO = M.NO)
    LEFT JOIN (
        SELECT BOARD_NO, COUNT(*) AS RECOMMEND_COUNT
        FROM BOARD_RECOMMEND
        GROUP BY BOARD_NO
    ) R ON (B.NO = R.BOARD_NO)
    WHERE B.DEL_YN = 'N'
    ORDER BY B.ENROLL_DATE DESC
)
WHERE ROWNUM <= 3
;

SELECT * FROM (
    SELECT N.NO, N.WRITER, A.NICK, N.TITLE, N.HIT, N.ENROLL_DATE
    FROM NOTICE N
    JOIN ADMIN A ON (N.WRITER = A.NO)
    WHERE DEL_YN = 'N'
    ORDER BY ENROLL_DATE DESC
)
WHERE ROWNUM <=3
;

SELECT * FROM (
    SELECT
        R.NO,
        R.MEMBER_NO,
        M.NICK,
        M.PROFILE,
        R.HOSPITAL_NO,
        H.NAME,
        R.TITLE,
        R.RATING,
        H.CITY,
        H.DISTRICT,
        R.ENROLL_DATE
    FROM REVIEW_BOARD R
    JOIN MEMBER M ON (R.MEMBER_NO = M.NO)
    JOIN HOSPITAL H ON (R.HOSPITAL_NO = H.NO)
    WHERE R.DEL_YN = 'N'
    AND R.ENROLL_DATE >= SYSDATE - 7
    ORDER BY R.RATING DESC, R.ENROLL_DATE DESC
)
WHERE ROWNUM <= 4

UNION ALL

SELECT * FROM (
    SELECT
        R.NO,
        R.MEMBER_NO,
        M.NICK,
        M.PROFILE,
        R.HOSPITAL_NO,
        H.NAME,
        R.TITLE,
        R.RATING,
        H.CITY,
        H.DISTRICT,
        R.ENROLL_DATE
    FROM  REVIEW_BOARD R
    JOIN MEMBER M ON (R.MEMBER_NO = M.NO)
        JOIN HOSPITAL H ON (R.HOSPITAL_NO = H.NO)
    WHERE R.DEL_YN = 'N'
    ORDER BY R.ENROLL_DATE DESC
)
WHERE ROWNUM <= 4
;

SELECT IMAGE_URL
FROM BANNER
WHERE SHOW_YN = 'Y'
AND DEL_YN = 'N'
ORDER BY NO DESC
;


------------------------------- ADMIN > BANNER -------------------------------
INSERT INTO BANNER
(
    NO
    , WRITER
    , TITLE
    , IMAGE_URL
    , SHOW_YN
)
VALUES
(
    SEQ_BANNER.NEXTVAL
    , #{writer}
    , #{title}
    , #{imageUrl}
    , #{showYn}
)
;
            
UPDATE BANNER
SET TITLE = #{title}
, SHOW_YN = #{showYn}
, IMAGE_URL = #{imageUrl}
, MODIFY_DATE = SYSDATE
WHERE NO = #{no}
AND DEL_YN = 'N'
;

UPDATE BANNER
SET DEL_YN = 'Y'
, MODIFY_DATE = SYSDATE
WHERE NO = #{no}
;

SELECT
    B.NO
    , B.WRITER
    , A.NICK
    , B.TITLE
    , B.IMAGE_URL
    , B.SHOW_YN
    , B.ENROLL_DATE
    , B.MODIFY_DATE
    , B.DEL_YN
FROM BANNER B
JOIN ADMIN A ON (B.WRITER = A.NO)
WHERE B.DEL_YN = 'N'

<if test="showYn != null and showYn != '' and showYn != '노출여부 전체'">
    AND B.SHOW_YN = #{showYn}
</if>

<if test="searchValue != null and searchValue != ''">
    AND B.TITLE LIKE '%${searchValue}%'
</if>

ORDER BY B.NO DESC
;

UPDATE BANNER
SET DEL_YN = 'Y'
, MODIFY_DATE = SYSDATE
WHERE NO IN
<foreach item='no' collection='no' open='(' separator=',' close=')'>
    #{no}
</foreach>
;


------------------------------------------------------------------------

SELECT D.DIET_DAY, SUM(M.KCAL) AS SUM_KCAL
FROM DIET D
LEFT JOIN MEAL_LOG M ON D.NO = M.DIET_NO
WHERE D.DEL_YN = 'N'
AND D.MEMBER_NO = 1
GROUP BY D.MEMBER_NO, D.DIET_DAY
;


SELECT 
    TO_CHAR(ENROLL_DATE, 'IW') AS WEEK, 
    AVG(AMOUNT) AS AMOUNT
FROM WATER_LOG
WHERE MEMBER_NO = 1 
  AND TO_CHAR(ENROLL_DATE, 'YYYY') = '2024'
GROUP BY TO_CHAR(ENROLL_DATE, 'IW')
ORDER BY WEEK
;

SELECT 
    TO_CHAR(D.DIET_DAY, 'IW') AS DIET_DAY, 
    ROUND(SUM(M.KCAL) / COUNT(DISTINCT D.DIET_DAY), 0) AS TOTAL_KCAL
FROM DIET D
LEFT JOIN MEAL_LOG M ON (D.NO = M.DIET_NO)
WHERE D.MEMBER_NO = 1
  AND TO_CHAR(D.DIET_DAY, 'YYYY') = '2025'
  AND D.DEL_YN = 'N'
GROUP BY TO_CHAR(D.DIET_DAY, 'IW')
ORDER BY DIET_DAY
;

--------------------------------------------------------------------------

SELECT
    TO_CHAR(SLEEP_START , 'HH24:MI') AS SLEEP_START
    , TO_CHAR(SLEEP_END , 'HH24:MI') AS SLEEP_END
FROM SLEEP
WHERE MEMBER_NO = 1
AND RECORD_DATE BETWEEN '2025-02-13' AND '2025-03-13'
ORDER BY SLEEP_START DESC
;

SELECT
    ALC_TYPE
    , ABV
    , CC
    , TO_CHAR(ENROLL_DATE, 'YYYY-MM-DD') AS ENROLL_DATE
FROM RECORD_ALC
WHERE MEMBER_NO = 1
AND ENROLL_DATE BETWEEN '2025-02-13' AND '2025-03-13'
ORDER BY ENROLL_DATE DESC
;

SELECT M.NAME
FROM USER_MEDICATION U
JOIN MEDICATION M ON (U.MEDICATION = M.NO)
WHERE U.MEMBER = 1
AND DEL_YN ='N'
;

SELECT 
     SYSTOLE
    , DIASTOLE
    , PULSE
    , TO_CHAR(ENROLL_DATE , 'YYYY-MM-DD') AS DAY
    , TO_CHAR(ENROLL_DATE , 'HH24:MI') AS TIME
    , NOTE
FROM BLOOD_PRESSURE
WHERE MEMBER_NO = 1
AND ENROLL_DATE BETWEEN '2025-02-13' AND '2025-03-13'
ORDER BY ENROLL_DATE DESC
;

SELECT 
    SUGAR
    , TO_CHAR(ENROLL_DATE , 'YYYY-MM-DD') AS DAY
    , TO_CHAR(ENROLL_DATE , 'HH24:MI') AS TIME
    , NOTE
FROM BLOOD_SUGAR
WHERE MEMBER_NO = 1
AND ENROLL_DATE BETWEEN '2025-02-13' AND '2025-03-13'
ORDER BY ENROLL_DATE DESC
;