-- DROP
DROP TABLE "MEMBER" CASCADE CONSTRAINT;
DROP TABLE "AEROBIC" CASCADE CONSTRAINT;
DROP TABLE "AEROBIC_BOOKMARK" CASCADE CONSTRAINTS;
DROP TABLE "AEROBIC_HISTORY" CASCADE CONSTRAINTS;
DROP TABLE "ANAEROBIC" CASCADE CONSTRAINT;
DROP TABLE "ANAEROBIC_BOOKMARK" CASCADE CONSTRAINTS;
DROP TABLE "ANAEROBIC_HISTORY" CASCADE CONSTRAINTS;
DROP TABLE "BOARD_RECOMMEND" CASCADE CONSTRAINT;
DROP TABLE "REVIEW_RECOMMEND" CASCADE CONSTRAINT;
DROP TABLE "BLOOD_PRESSURE" CASCADE CONSTRAINT;
DROP TABLE "BLOOD_SUGAR" CASCADE CONSTRAINT;
DROP TABLE "SLEEP" CASCADE CONSTRAINT;
DROP TABLE "INSULIN" CASCADE CONSTRAINT;
DROP TABLE "REPORTED_HONEY_TIP" CASCADE CONSTRAINT;
DROP TABLE "HOSPITAL" CASCADE CONSTRAINT;
DROP TABLE "REPORT_TYPE" CASCADE CONSTRAINT;
DROP TABLE "REPORTED_BOARD_COMMENT" CASCADE CONSTRAINT;
DROP TABLE "NOTICE" CASCADE CONSTRAINT;
DROP TABLE "DEPARTMENT" CASCADE CONSTRAINT;
DROP TABLE "ALC_TYPE" CASCADE CONSTRAINT;
DROP TABLE "BODYPART" CASCADE CONSTRAINT;
DROP TABLE "BOARD" CASCADE CONSTRAINT;
DROP TABLE "DIET" CASCADE CONSTRAINT;
DROP TABLE "WATER_LOG" CASCADE CONSTRAINT;
DROP TABLE "FOOD" CASCADE CONSTRAINT;
DROP TABLE "BOARD_COMMENT" CASCADE CONSTRAINT;
DROP TABLE "DETAIL_BODYPART" CASCADE CONSTRAINT;
DROP TABLE "SYMPTOM" CASCADE CONSTRAINT;
DROP TABLE "BODY_SYMPTOM" CASCADE CONSTRAINT;
DROP TABLE "PUBLIC_HEALTH_CENTER" CASCADE CONSTRAINT;
DROP TABLE "MEDICATION" CASCADE CONSTRAINT;
DROP TABLE "MEAL_LOG" CASCADE CONSTRAINT;
DROP TABLE "DRUG_FORM" CASCADE CONSTRAINT;
DROP TABLE DRUG_COLOR CASCADE CONSTRAINT;
DROP TABLE "USER_MEDICATION" CASCADE CONSTRAINT;
DROP TABLE "CATEGORY" CASCADE CONSTRAINT;
DROP TABLE "PHARMACY" CASCADE CONSTRAINT;
DROP TABLE "HOSPITAL_DEPARTMENT" CASCADE CONSTRAINT;
DROP TABLE "PUSH_NOTIFICATION" CASCADE CONSTRAINT;
DROP TABLE "MEAL_CODE" CASCADE CONSTRAINT;
DROP TABLE "PUSH_SETTING" CASCADE CONSTRAINT;
DROP TABLE "RECOMMENDATION" CASCADE CONSTRAINT;
DROP TABLE "RECORD_ALC" CASCADE CONSTRAINT;
DROP TABLE "RECORD_CIGARETTE" CASCADE CONSTRAINT;
DROP TABLE "DOCTOR" CASCADE CONSTRAINT;
DROP TABLE "ADMIN" CASCADE CONSTRAINT;
DROP TABLE "COMPANY" CASCADE CONSTRAINT;
DROP TABLE "COMPANY_DEPT" CASCADE CONSTRAINT;
DROP TABLE "REPORTED_REVIEW" CASCADE CONSTRAINT;
DROP TABLE "REVIEW_BOARD" CASCADE CONSTRAINT;
DROP TABLE "NOTICE_ATTACHMENT" CASCADE CONSTRAINT;
DROP TABLE "BOARD_ATTACHMENT" CASCADE CONSTRAINT;
DROP TABLE "CITY" CASCADE CONSTRAINT;
DROP TABLE "DISTRICT" CASCADE CONSTRAINT;
DROP TABLE "DONG" CASCADE CONSTRAINT;
DROP TABLE "TIMETABLE" CASCADE CONSTRAINT;
DROP TABLE "PUSH_CODE" CASCADE CONSTRAINT;
DROP TABLE "HOSPITAL_TIME" CASCADE CONSTRAINT;
DROP TABLE "PHARMACY_TIME" CASCADE CONSTRAINT;
DROP TABLE "PUBLIC_HEALTH_CENTER_TIME" CASCADE CONSTRAINT;
DROP TABLE "WEIGHT_LOG" CASCADE CONSTRAINT;
DROP TABLE "REVIEW_ATTACHMENT" CASCADE CONSTRAINT;
DROP TABLE "CHALLENGER_POST" CASCADE CONSTRAINTS;
DROP TABLE "CHALLENGER_MEMBER" CASCADE CONSTRAINTS;
DROP TABLE "CHALLENGER" CASCADE CONSTRAINTS;
DROP TABLE "LEVEL" CASCADE CONSTRAINTS;
DROP TABLE "DASHBOARD" CASCADE CONSTRAINTS;
DROP TABLE "BANNER" CASCADE CONSTRAINTS;
DROP TABLE "REPORTED_REVIEW_COMMENT" CASCADE CONSTRAINTS;
DROP TABLE "REVIEW_COMMENT" CASCADE CONSTRAINTS;
DROP TABLE "NOTIFICATION_SETTINGS" CASCADE CONSTRAINTS;
DROP TABLE "NOTIFICATION" CASCADE CONSTRAINTS;

-- SEQUENCE
DROP SEQUENCE SEQ_USER_MEDICATION;
CREATE SEQUENCE SEQ_USER_MEDICATION NOCYCLE NOCACHE;

DROP SEQUENCE SEQ_MEDICATION;
CREATE SEQUENCE SEQ_MEDICATION NOCYCLE NOCACHE;

DROP SEQUENCE SEQ_MEMBER;
CREATE SEQUENCE SEQ_MEMBER NOCYCLE NOCACHE;
DROP SEQUENCE SEQ_AEROBIC;
CREATE SEQUENCE SEQ_AEROBIC NOCYCLE NOCACHE;
DROP SEQUENCE SEQ_AEROBIC_HISTORY;
CREATE SEQUENCE SEQ_AEROBIC_HISTORY
  START WITH 508
  INCREMENT BY 1
  NOCACHE NOCYCLE;
DROP SEQUENCE SEQ_AEROBIC_BOOKMARK;
CREATE SEQUENCE SEQ_AEROBIC_BOOKMARK NOCYCLE NOCACHE;
DROP SEQUENCE SEQ_ANAEROBIC;
CREATE SEQUENCE SEQ_ANAEROBIC NOCYCLE NOCACHE;
DROP SEQUENCE SEQ_ANAEROBIC_HISTORY;
CREATE SEQUENCE SEQ_ANAEROBIC_HISTORY
  START WITH 1038
  INCREMENT BY 1
  NOCACHE NOCYCLE;
DROP SEQUENCE SEQ_ANAEROBIC_BOOKMARK;
CREATE SEQUENCE SEQ_ANAEROBIC_BOOKMARK NOCYCLE NOCACHE;
DROP SEQUENCE SEQ_BLOOD_PRESSURE;
CREATE SEQUENCE SEQ_BLOOD_PRESSURE NOCYCLE NOCACHE;
DROP SEQUENCE SEQ_BLOOD_SUGAR;
CREATE SEQUENCE SEQ_BLOOD_SUGAR NOCYCLE NOCACHE;
DROP SEQUENCE SEQ_SLEEP;
CREATE SEQUENCE SEQ_SLEEP NOCYCLE NOCACHE;
DROP SEQUENCE SEQ_INSULIN;
CREATE SEQUENCE SEQ_INSULIN NOCYCLE NOCACHE;
DROP SEQUENCE SEQ_REPORTED_HONEY_TIP;
CREATE SEQUENCE SEQ_REPORTED_HONEY_TIP NOCYCLE NOCACHE;
DROP SEQUENCE SEQ_HOSPITAL;
CREATE SEQUENCE SEQ_HOSPITAL NOCYCLE NOCACHE;
DROP SEQUENCE SEQ_REPORT_TYPE;
CREATE SEQUENCE SEQ_REPORT_TYPE NOCYCLE NOCACHE;
DROP SEQUENCE SEQ_REPORTED_BOARD_COMMENT;
CREATE SEQUENCE SEQ_REPORTED_BOARD_COMMENT NOCYCLE NOCACHE;
DROP SEQUENCE SEQ_NOTICE;
CREATE SEQUENCE SEQ_NOTICE NOCYCLE NOCACHE;
DROP SEQUENCE SEQ_DEPARTMENT;
CREATE SEQUENCE SEQ_DEPARTMENT NOCYCLE NOCACHE;
DROP SEQUENCE SEQ_ALC_TYPE;
CREATE SEQUENCE SEQ_ALC_TYPE NOCYCLE NOCACHE;
DROP SEQUENCE SEQ_BODYPART;
CREATE SEQUENCE SEQ_BODYPART NOCYCLE NOCACHE;
DROP SEQUENCE SEQ_BOARD;
CREATE SEQUENCE SEQ_BOARD NOCYCLE NOCACHE;
DROP SEQUENCE SEQ_DIET;
CREATE SEQUENCE SEQ_DIET NOCYCLE NOCACHE;
DROP SEQUENCE SEQ_WATER_LOG;
CREATE SEQUENCE SEQ_WATER_LOG NOCYCLE NOCACHE;
DROP SEQUENCE SEQ_FOOD;
CREATE SEQUENCE SEQ_FOOD NOCYCLE NOCACHE;
DROP SEQUENCE SEQ_BOARD_COMMENT;
CREATE SEQUENCE SEQ_BOARD_COMMENT NOCYCLE NOCACHE;
DROP SEQUENCE SEQ_DETAIL_BODYPART;
CREATE SEQUENCE SEQ_DETAIL_BODYPART NOCYCLE NOCACHE;
DROP SEQUENCE SEQ_SYMPTOM;
CREATE SEQUENCE SEQ_SYMPTOM NOCYCLE NOCACHE;
DROP SEQUENCE SEQ_BODY_SYMPTOM;
CREATE SEQUENCE SEQ_BODY_SYMPTOM NOCYCLE NOCACHE;
DROP SEQUENCE SEQ_PUBLIC_HEALTH_CENTER;
CREATE SEQUENCE SEQ_PUBLIC_HEALTH_CENTER NOCYCLE NOCACHE;
DROP SEQUENCE SEQ_MEAL_LOG;
CREATE SEQUENCE SEQ_MEAL_LOG NOCYCLE NOCACHE;
DROP SEQUENCE SEQ_DRUG_FORM;
CREATE SEQUENCE SEQ_DRUG_FORM NOCYCLE NOCACHE;
DROP SEQUENCE SEQ_DRUG_COLOR;
CREATE SEQUENCE SEQ_DRUG_COLOR NOCYCLE NOCACHE;

DROP SEQUENCE SEQ_CATEGORY;
CREATE SEQUENCE SEQ_CATEGORY NOCYCLE NOCACHE;
DROP SEQUENCE SEQ_PHARMACY;
CREATE SEQUENCE SEQ_PHARMACY NOCYCLE NOCACHE;
DROP SEQUENCE SEQ_HOSPITAL_DEPARTMENT;
CREATE SEQUENCE SEQ_HOSPITAL_DEPARTMENT NOCYCLE NOCACHE;
DROP SEQUENCE SEQ_PUSH_NOTIFICATION;
CREATE SEQUENCE SEQ_PUSH_NOTIFICATION NOCYCLE NOCACHE;
DROP SEQUENCE SEQ_MEAL_CODE;
CREATE SEQUENCE SEQ_MEAL_CODE NOCYCLE NOCACHE;
DROP SEQUENCE SEQ_PUSH_SETTING;
CREATE SEQUENCE SEQ_PUSH_SETTING NOCYCLE NOCACHE;
DROP SEQUENCE SEQ_RECOMMENDATION;
CREATE SEQUENCE SEQ_RECOMMENDATION NOCYCLE NOCACHE;
DROP SEQUENCE SEQ_RECORD_ALC;
CREATE SEQUENCE SEQ_RECORD_ALC NOCYCLE NOCACHE;
DROP SEQUENCE SEQ_RECORD_CIGARETTE;
CREATE SEQUENCE SEQ_RECORD_CIGARETTE NOCYCLE NOCACHE;
DROP SEQUENCE SEQ_DOCTOR;
CREATE SEQUENCE SEQ_DOCTOR NOCYCLE NOCACHE;
DROP SEQUENCE SEQ_ADMIN;
CREATE SEQUENCE SEQ_ADMIN NOCYCLE NOCACHE;
DROP SEQUENCE SEQ_COMPANY;
CREATE SEQUENCE SEQ_COMPANY NOCYCLE NOCACHE;
DROP SEQUENCE SEQ_COMPANY_DEPT;
CREATE SEQUENCE SEQ_COMPANY_DEPT NOCYCLE NOCACHE;
DROP SEQUENCE SEQ_REPORTED_REVIEW;
CREATE SEQUENCE SEQ_REPORTED_REVIEW NOCYCLE NOCACHE;
DROP SEQUENCE SEQ_CIGARETTE;
CREATE SEQUENCE SEQ_CIGARETTE NOCYCLE NOCACHE;
DROP SEQUENCE SEQ_REVIEW_BOARD;
CREATE SEQUENCE SEQ_REVIEW_BOARD NOCYCLE NOCACHE;
DROP SEQUENCE SEQ_NOTICE_ATTACHMENT;
CREATE SEQUENCE SEQ_NOTICE_ATTACHMENT NOCYCLE NOCACHE;
DROP SEQUENCE SEQ_BOARD_ATTACHMENT;
CREATE SEQUENCE SEQ_BOARD_ATTACHMENT NOCYCLE NOCACHE;
DROP SEQUENCE SEQ_CITY;
CREATE SEQUENCE SEQ_CITY NOCYCLE NOCACHE;
DROP SEQUENCE SEQ_DISTRICT;
CREATE SEQUENCE SEQ_DISTRICT NOCYCLE NOCACHE;
DROP SEQUENCE SEQ_DONG;
CREATE SEQUENCE SEQ_DONG NOCYCLE NOCACHE;
DROP SEQUENCE SEQ_TIMETABLE;
CREATE SEQUENCE SEQ_TIMETABLE NOCYCLE NOCACHE;
DROP SEQUENCE SEQ_PUSH_CODE;
CREATE SEQUENCE SEQ_PUSH_CODE NOCYCLE NOCACHE;
DROP SEQUENCE SEQ_HOSPITAL_TIME;
CREATE SEQUENCE SEQ_HOSPITAL_TIME NOCYCLE NOCACHE;
DROP SEQUENCE SEQ_PHARMACY_TIME;
CREATE SEQUENCE SEQ_PHARMACY_TIME NOCYCLE NOCACHE;
DROP SEQUENCE SEQ_PUBLIC_HEALTH_CENTER_TIME;
CREATE SEQUENCE SEQ_PUBLIC_HEALTH_CENTER_TIME NOCYCLE NOCACHE;
DROP SEQUENCE SEQ_WEIGHT_LOG;
CREATE SEQUENCE SEQ_WEIGHT_LOG NOCYCLE NOCACHE;
DROP SEQUENCE SEQ_REVIEW_ATTACHMENT;
CREATE SEQUENCE SEQ_REVIEW_ATTACHMENT NOCYCLE NOCACHE;
DROP SEQUENCE SEQ_CHALLENGER_POST;
DROP SEQUENCE SEQ_CHALLENGER_MEMBER;
DROP SEQUENCE SEQ_CHALLENGER;
DROP SEQUENCE SEQ_LEVEL;
CREATE SEQUENCE SEQ_LEVEL NOCYCLE NOCACHE;
CREATE SEQUENCE SEQ_CHALLENGER NOCYCLE NOCACHE;
CREATE SEQUENCE SEQ_CHALLENGER_MEMBER NOCYCLE NOCACHE;
CREATE SEQUENCE SEQ_CHALLENGER_POST NOCYCLE NOCACHE;
DROP SEQUENCE SEQ_DASHBOARD;
CREATE SEQUENCE SEQ_DASHBOARD NOCYCLE NOCACHE;
DROP SEQUENCE SEQ_BANNER;
CREATE SEQUENCE SEQ_BANNER NOCYCLE NOCACHE;
DROP SEQUENCE SEQ_REPORTED_REVIEW_COMMENT;
CREATE SEQUENCE SEQ_REPORTED_REVIEW_COMMENT NOCYCLE NOCACHE;
DROP SEQUENCE SEQ_REVIEW_COMMENT;
CREATE SEQUENCE SEQ_REVIEW_COMMENT NOCYCLE NOCACHE;
DROP SEQUENCE SEQ_NOTIFICATION_SETTINGS;
CREATE SEQUENCE SEQ_NOTIFICATION_SETTINGS NOCACHE NOCYCLE;
DROP SEQUENCE SEQ_NOTIFICATION;
CREATE SEQUENCE SEQ_NOTIFICATION NOCACHE NOCYCLE;


-- CREATE
CREATE TABLE "MEMBER" (
	"NO"	NUMBER		            PRIMARY KEY,
	"NAME"	VARCHAR2(20)		    NOT NULL,
	"ID"	VARCHAR2(30)		    NOT NULL,
	"PWD"	VARCHAR2(100)		    NOT NULL,
	"NICK"	VARCHAR2(40)		    NOT NULL,
	"EMAIL"	VARCHAR2(40)		    NOT NULL,
	"ADDRESS"	VARCHAR2(1000)	    NOT NULL,
	"HEIGHT"	NUMBER		        NULL,
	"WEIGHT"	NUMBER		        NULL,
	"PROFILE"	VARCHAR2(1000)	    NULL,
	"GENDER"	CHAR(1)		        NULL,
	"ENROLL_DATE"	DATE		    NULL,
	"PHONE"	    VARCHAR2(20)	        NOT NULL,
	"DEL_YN"	CHAR(1)     	    DEFAULT 'N'	NULL,
    "LEVEL" NUMBER DEFAULT 1,
    "EXP" NUMBER DEFAULT 0
);

CREATE TABLE "AEROBIC" (
    "NO"            NUMBER PRIMARY KEY,             -- 운동 NO
    "NAME"          VARCHAR2(100) NOT NULL,         -- 운동 이름
    "DESCRIPTION"   CLOB,                           -- 운동 설명
    "IMAGE_URL"     VARCHAR2(1000),                 -- 운동 GIF 또는 이미지 URL
    "GUIDE"         CLOB,                           -- 운동 가이드 (줄바꿈 포함)
    "CAL_CONSUME"   NUMBER	NOT NULL                -- 칼로리 소모량
);

CREATE TABLE "AEROBIC_BOOKMARK" (
    NO NUMBER PRIMARY KEY,  -- 북마크 ID
    USER_NO NUMBER NOT NULL,  -- 유저 ID (MEMBER 테이블의 NO)
    EX_NO NUMBER NOT NULL,  -- 운동 ID (ANAEROBIC 테이블의 NO)
    CONSTRAINT FK_BOOKMARK_USER FOREIGN KEY (USER_NO) REFERENCES MEMBER(NO) ON DELETE CASCADE,
    CONSTRAINT FK_BOOKMARK_EX FOREIGN KEY (EX_NO) REFERENCES AEROBIC(NO) ON DELETE CASCADE
);

CREATE TABLE "AEROBIC_HISTORY" (
    NO              NUMBER PRIMARY KEY,               -- 유산소 운동 내역 고유 ID (기본키)
    USER_NO         NUMBER NOT NULL,                  -- 유저 번호 (외래키)
    EX_NO           NUMBER NOT NULL,                  -- 운동 번호 (외래키)
    EX_DATE         DATE NOT NULL,                    -- 운동일
    EX_DURATION     NUMBER(5) CHECK (EX_DURATION >= 0),  -- 운동시간(분 단위), 0 이상 값만 허용
    START_TIME      TIMESTAMP NOT NULL,               -- 운동 시작 시간
    END_TIME        TIMESTAMP NOT NULL,               -- 운동 종료 시간

    -- 시작 시간이 종료 시간보다 앞서야 하는 테이블 단위 CHECK 제약 조건 추가
    CONSTRAINT CHK_TIME CHECK (START_TIME < END_TIME), 
    -- 외래 키 설정 (유저 테이블)
    CONSTRAINT FK_USER FOREIGN KEY (USER_NO) REFERENCES MEMBER(NO) ON DELETE CASCADE,
    -- 외래 키 설정 (운동 테이블)
    CONSTRAINT FK_EXERCISE FOREIGN KEY (EX_NO) REFERENCES AEROBIC(NO) ON DELETE CASCADE
);

CREATE TABLE "ANAEROBIC" (
    "NO"            NUMBER PRIMARY KEY,             -- 운동 NO
    "NAME"          VARCHAR2(100) NOT NULL,         -- 운동 이름
    "DESCRIPTION"   CLOB,                           -- 운동 설명
    "IMAGE_URL"     VARCHAR2(1000),                 -- 운동 GIF 또는 이미지 URL
    "GUIDE"         CLOB,                           -- 운동 가이드 (줄바꿈 포함)
    "CAL_CONSUME"   NUMBER	NOT NULL,               -- 칼로리 소모량(회당)
    "EX_PART"       VARCHAR2(255)                   -- 타겟 근육 (쉼표로 구분)
);

CREATE TABLE "ANAEROBIC_BOOKMARK" (
    NO NUMBER PRIMARY KEY,  -- 북마크 ID
    USER_NO NUMBER NOT NULL,  -- 유저 ID (MEMBER 테이블의 NO)
    EX_NO NUMBER NOT NULL,  -- 운동 ID (ANAEROBIC 테이블의 NO)
    CONSTRAINT FK_ANAEROBIC_BOOKMARK_USER FOREIGN KEY (USER_NO) REFERENCES MEMBER(NO) ON DELETE CASCADE,
    CONSTRAINT FK_ANAEROBIC_BOOKMARK_EX FOREIGN KEY (EX_NO) REFERENCES ANAEROBIC(NO) ON DELETE CASCADE
);

CREATE TABLE "ANAEROBIC_HISTORY" (
    NO              NUMBER PRIMARY KEY,               -- 유산소 운동 내역 고유 ID (기본키)
    USER_NO         NUMBER NOT NULL,                  -- 유저 번호 (외래키)
    EX_NO           NUMBER NOT NULL,                  -- 운동 번호 (외래키)
    EX_DATE         DATE NOT NULL,                    -- 운동일
    WEIGHT          NUMBER,                            -- 운동시간(분 단위), 0 이상 값만 허용
    REPS            NUMBER NOT NULL,

    -- 외래 키 설정 (유저 테이블)
    CONSTRAINT FK_ANUSER FOREIGN KEY (USER_NO) REFERENCES MEMBER(NO) ON DELETE CASCADE,
    -- 외래 키 설정 (운동 테이블)
    CONSTRAINT FK_ANAEROBIC FOREIGN KEY (EX_NO) REFERENCES ANAEROBIC(NO) ON DELETE CASCADE
);


CREATE TABLE "BLOOD_PRESSURE" (
	"NO"	NUMBER		NOT NULL,
	"MEMBER_NO"	NUMBER		NOT NULL,
	"SYSTOLE"	NUMBER		NOT NULL,
	"DIASTOLE"	NUMBER		NOT NULL,
	"PULSE"	NUMBER		NULL,
    NOTE        VARCHAR2(255)   DEFAULT '없음' NOT NULL ,
	"ENROLL_DATE"	DATE		DEFAULT SYSDATE NOT NULL
);


CREATE TABLE "BLOOD_SUGAR" (
	"NO"	NUMBER		NOT NULL,
	"MEMBER_NO"	NUMBER		NOT NULL,
	"SUGAR"	NUMBER		NULL,
     NOTE        VARCHAR2(255)  DEFAULT '없음' NOT NULL,
	"ENROLL_DATE"	DATE		DEFAULT SYSDATE NOT NULL
);

CREATE TABLE "SLEEP" (
	"NO"	NUMBER		NOT NULL,
	"MEMBER_NO"	NUMBER		NOT NULL,
	"SLEEP_START"	DATE		NOT NULL,
	"SLEEP_END"	DATE		NOT NULL,
	"SLEEP_DURATION"	NUMBER		NOT NULL,
    "SLEEP_DURATION_HOUR"	VARCHAR2(20)		NOT NULL,
	"RECORD_DATE"	DATE	DEFAULT SYSDATE	NULL
);


CREATE TABLE "INSULIN" (
	"NO"	NUMBER		NOT NULL,
	"MEMBER_NO"	NUMBER		NOT NULL,
	"POINT"	NUMBER		NOT NULL,
	"ENROLL_DATE"	DATE		DEFAULT SYSDATE NOT NULL,
    NOTE    VARCHAR2(255)   NULL,
	"ABLE_DATE"	DATE		NULL
);

CREATE TABLE "REPORTED_HONEY_TIP" (
	"NO"	NUMBER		NOT NULL,
	"REPORT_TYPE"	NUMBER		NOT NULL,
	"BOARD_NO"	NUMBER		NOT NULL,
	"MEMBER_NO"	NUMBER		NOT NULL,
	"DEL_YN"	CHAR(1)     	    DEFAULT 'N'	NULL,
	"ENROLL_DATE"	DATE	DEFAULT SYSDATE	NOT NULL
);
CREATE TABLE "HOSPITAL" (
	"NO"	NUMBER		NOT NULL,
	"NAME"	VARCHAR2(100)		NOT NULL,
    "HOSPITAL_TYPE" VARCHAR2(100) NULL,
    "CITY" VARCHAR2(100)         NULL,
    "DISTRICT" VARCHAR2(100)         NULL,
    "DONG" VARCHAR2(100)         NULL,
	"ADDRESS"	VARCHAR2(1000)		NOT NULL,
	"TELL_NUM"	VARCHAR2(20)		NULL,
    "POST_NUM"	VARCHAR2(20)		NULL,
	"OPEN_YN"	CHAR(1)		NULL,
	"LOCATION_X"	NUMBER		NULL,
	"LOCATION_Y"	NUMBER		NULL
);

CREATE TABLE "REPORT_TYPE" (
	"NO"	NUMBER		NOT NULL,
	"NAME"	VARCHAR2(100)		NOT NULL
);

CREATE TABLE "REPORTED_BOARD_COMMENT" (
	"NO"	NUMBER		NOT NULL,
	"REPORT_TYPE"	NUMBER		NOT NULL,
	"COMMENT_NO"	NUMBER		NOT NULL,
	"MEMBER_NO"	NUMBER		NOT NULL,
	"ENROLL_DATE"	DATE	DEFAULT SYSDATE	NOT NULL
);

CREATE TABLE "NOTICE" (
	"NO"	NUMBER		NOT NULL,
	"WRITER"	NUMBER		NOT NULL,
	"TITLE"	VARCHAR2(255)		NOT NULL,
	"CONTENT"	CLOB		NOT NULL,
	"ENROLL_DATE"	DATE	DEFAULT SYSDATE	NOT NULL,
	"MODIFY_DATE"	DATE		NULL,
	"HIT"	NUMBER	DEFAULT '0'	NOT NULL,
	"DEL_YN"	CHAR(1)	DEFAULT 'N'	NOT NULL
);

CREATE TABLE "DEPARTMENT" (
	"NO"	NUMBER		NOT NULL,
	"DEPT_NAME"	VARCHAR2(50)		NOT NULL
);

CREATE TABLE "ALC_TYPE" (
	"NO"	NUMBER		NOT NULL,
	"ALC_TYPE"	VARCHAR2(100)		NOT NULL,
	"ABV"	NUMBER		NOT NULL
);

CREATE TABLE "BODYPART" (
	"NO"	NUMBER		NULL,
	"PART"	VARCHAR2(50)		NOT NULL
);

CREATE TABLE "BOARD" (
	"NO"	NUMBER		NOT NULL,
	"CATEGORY_NO"	NUMBER		NOT NULL,
	"MEMBER_NO"	NUMBER		NOT NULL,
	"TITLE"	VARCHAR2(1000)		NOT NULL,
	"CONTENT"	CLOB		NOT NULL,
	"HIT"	NUMBER		        DEFAULT '0'    NOT NULL,
	"ENROLL_DATE"	DATE		DEFAULT SYSDATE    NOT NULL,
	"MODIFY_DATE"	DATE		NULL,
	"DEL_YN"	CHAR(1)		    DEFAULT 'N'    NOT NULL
);


CREATE TABLE "DIET" (
	"NO"	NUMBER		NOT NULL,
	"MEMBER_NO"	NUMBER		NOT NULL,
	"MEAL_CODE"	NUMBER		NOT NULL,
	"DIET_DAY"	DATE		NOT NULL,
	"MEMO"	VARCHAR(2000)		NULL,
	"IMAGE"	VARCHAR(2000)		NULL,
	"ENROLL_DATE"	DATE		DEFAULT SYSDATE    NOT NULL,
	"MODIFY_DATE"	DATE		NULL,
	"DEL_YN"	CHAR(1)		  	DEFAULT 'N'    NOT NULL
);

CREATE TABLE "WATER_LOG" (
	"NO"	NUMBER		NOT NULL,
	"MEMBER_NO"	NUMBER		NOT NULL,
	"ENROLL_DATE"	DATE		NOT NULL,
	"AMOUNT"	NUMBER		NOT NULL
);

CREATE TABLE "FOOD" (
	"NO"	NUMBER		NOT NULL,
	"NAME"	VARCHAR2(1000)		NOT NULL,
    	"UNIT"    VARCHAR2(1000) 		NOT NULL ,
	"AMOUNT"	NUMBER		NOT NULL,
	"KCAL"	NUMBER		NOT NULL
);

CREATE TABLE "BOARD_COMMENT" (
	"NO"	NUMBER		NOT NULL,
	"MEMBER_NO"	NUMBER		NOT NULL,
	"BOARD_NO"	NUMBER		NOT NULL,
	"CONTENT"	VARCHAR2(2000)		NOT NULL,
	"ENROLL_DATE"	DATE  DEFAULT SYSDATE		NOT NULL,
	"MODIFY_DATE"	DATE		NULL,
	"DEL_YN"	CHAR(1)		DEFAULT 'N' NOT NULL,
	"NOTIFIED_YN" CHAR(1) DEFAULT 'N'
);

CREATE TABLE "DETAIL_BODYPART" (
	"NO"	NUMBER		NULL,
	"BODYPART"	NUMBER		NULL,
	"DETAILPART"	VARCHAR2(50)		NULL
);

CREATE TABLE "SYMPTOM" (
	"NO"	NUMBER		NULL,
	"DETAILPART"	NUMBER		NULL,
	"SYMPTOM"	VARCHAR2(50)		NOT NULL
);

CREATE TABLE "BODY_SYMPTOM" (
	"NO"	NUMBER		NOT NULL,
	"SYMPTOM"	NUMBER		NULL
);

CREATE TABLE "PUBLIC_HEALTH_CENTER" (
	"NO"	NUMBER		NOT NULL,
	"NAME"	VARCHAR2(100)		NOT NULL,
  "CITY" VARCHAR2(100)         NULL,
  "DISTRICT" VARCHAR2(100)         NULL,
  "DONG" VARCHAR2(100)         NULL,
	"ADDRESS"	VARCHAR2(1000)		NOT NULL,
	"TELL_NUM"	VARCHAR2(20)		NULL,
  "POST_NUM"	VARCHAR2(20)		NULL,
	"OPEN_YN"	CHAR(1)		NULL,
	"LOCATION_X"	NUMBER		NULL,
	"LOCATION_Y"	NUMBER		NULL
);

CREATE TABLE "MEDICATION" (
   "NO"   NUMBER      NOT NULL,
   "NAME"   VARCHAR2(100)      NOT NULL,
   "IMAGE_URL"   VARCHAR2(3000)      NULL,
   "FORM"   NUMBER      NOT NULL,
    "COLOR1" NUMBER      NOT NULL, 
    "COLOR2" NUMBER      NULL, 
   "EFFECT"   VARCHAR2(4000)      NOT NULL,
   "SIDEEFFECT"   VARCHAR2(4000)      NOT NULL,
   "PRECAUTION"   VARCHAR2(4000)      NOT NULL,
   "DOSAGE"   VARCHAR2(4000)      NOT NULL,
    "COLOR" VARCHAR2(20)       NOT NULL
);



CREATE TABLE "MEAL_LOG" (
	"NO"	NUMBER		NOT NULL,
	"DIET_NO"	NUMBER		NOT NULL,
	"NAME"	VARCHAR2(1000)		NOT NULL,
    "UNIT"    VARCHAR2(1000) 		NOT NULL ,
	"AMOUNT"	NUMBER		NOT NULL,
	"KCAL"	NUMBER		NOT NULL
);

CREATE TABLE "DRUG_FORM"  (
    "NO" NUMBER NOT NULL,
    "FORM" VARCHAR2(30) NOT NULL
);

CREATE TABLE "DRUG_COLOR"  (
    "NO" NUMBER NOT NULL,
    "COLOR" VARCHAR2(30) NOT NULL
);

CREATE TABLE "USER_MEDICATION" (
   "NO"   NUMBER      NOT NULL,
   "MEDICATION"   NUMBER      NOT NULL,
   "MEMBER"   NUMBER      NOT NULL,
   "START_DATE"   DATE      NULL,
   "END_DATE"   DATE      NULL,
   "NOTES"   VARCHAR2(1000)      NULL,
   "DEL_YN"   CHAR(1)   DEFAULT 'N'   NULL,
   "DEL_TIME"   DATE   DEFAULT SYSDATE   NULL
);


CREATE TABLE "CATEGORY" (
	"NO"	NUMBER		NOT NULL,
	"NAME"	VARCHAR2(100)		NOT NULL
);

CREATE TABLE "PHARMACY" (
	"NO"	NUMBER		NOT NULL,
	"NAME"	VARCHAR2(100)		NOT NULL,
  "CITY" VARCHAR2(100)         NULL,
  "DISTRICT" VARCHAR2(100)         NULL,
  "DONG" VARCHAR2(100)         NULL,
	"ADDRESS"	VARCHAR2(1000)		NOT NULL,
	"TELL_NUM"	VARCHAR2(20)		NULL,
  "POST_NUM"	VARCHAR2(20)		NULL,
	"OPEN_YN"	CHAR(1)		NULL,
	"LOCATION_X"	NUMBER		NULL,
	"LOCATION_Y"	NUMBER		NULL
);

CREATE TABLE "HOSPITAL_DEPARTMENT" (
	"NO"	NUMBER		NOT NULL,
	"HOSPITAL"	NUMBER		NOT NULL,
	"DEPT"	NUMBER		NOT NULL
);

COMMENT ON COLUMN "HOSPITAL_DEPARTMENT"."HOSPITAL" IS 'SEQ_HOSPITAL';


CREATE TABLE "PUSH_NOTIFICATION" (
	"NO"	NUMBER		NOT NULL,
	"PUSH_CODE"	NUMBER		NOT NULL,
	"MEMBER_NO"	NUMBER		NOT NULL,
	"CONTENT"	VARCHAR2(500)		NOT NULL,
	"OCCUR_TIME"	DATE	DEFAULT SYSDATE	NOT NULL,
	"DEL_YN"	CHAR(1)	DEFAULT 'N'	NOT NULL
);

CREATE TABLE "MEAL_CODE" (
	"NO"	NUMBER		NOT NULL,
	"NAME"	VARCHAR2(50)		NOT NULL
);

COMMENT ON COLUMN "MEAL_CODE"."NAME" IS '??ħ, ????, ????, ????, ???';

CREATE TABLE "PUSH_SETTING" (
	"NO"	NUMBER		NOT NULL,
	"MEMBER_NO"	NUMBER		NOT NULL,
	"PUSH_CODE"	NUMBER		NOT NULL,
	"SETTING"	CHAR(1)	DEFAULT 'Y'	NOT NULL
);

COMMENT ON COLUMN "PUSH_SETTING"."SETTING" IS 'Y/N';

CREATE TABLE "RECOMMENDATION" (
	"BOARD_NO"	NUMBER		NOT NULL,
	"MEMBER_NO"	NUMBER		NOT NULL
);

CREATE TABLE "RECORD_ALC" (
	"NO"	NUMBER		NOT NULL,
	"MEMBER_NO"	NUMBER		NOT NULL,
	"ALC_TYPE"	VARCHAR2(100)		NOT NULL,
	"ABV"	NUMBER		NOT NULL,
	"CC"	NUMBER		NOT NULL,
	"ENROLL_DATE"	DATE		NOT NULL
);

CREATE TABLE "RECORD_CIGARETTE" (
	"NO"	NUMBER		NOT NULL,
	"MEMBER_NO"	NUMBER		NOT NULL,
	"CIGARETTE"	VARCHAR2(100)		NOT NULL,
	"START_DATE"	DATE		NULL,
	"END_DATE"	DATE		NULL,
    "TAR" NUMBER       NULL
);

CREATE TABLE "DOCTOR" (
	"NO"	NUMBER		NOT NULL,
	"HOSPITAL"	NUMBER		NOT NULL,
	"DEPARTMENT"	NUMBER		NOT NULL,
	"NAME"	VARCHAR2(100)		NULL
);


CREATE TABLE "ADMIN" (
	"NO"	NUMBER		NOT NULL,
	"NICK"	VARCHAR2(200)		NOT NULL,
	"ID"	VARCHAR2(200)		NOT NULL,
	"PWD"	VARCHAR2(200)		NOT NULL
);

CREATE TABLE "COMPANY" (
	"NO"	NUMBER		NOT NULL,
	"NAME"	VARCHAR2(500)		NOT NULL
);

CREATE TABLE "COMPANY_DEPT" (
	"NO"	NUMBER		NOT NULL,
	"COMPANY_NO"	NUMBER		NOT NULL,
	"NAME"	VARCHAR2(500)		NOT NULL
);

CREATE TABLE "REPORTED_REVIEW" (
	"NO"	NUMBER		NOT NULL,
	"REPORT_TYPE"	NUMBER		NOT NULL,
	"REVIEW_NO"	NUMBER		NOT NULL,
	"MEMBER_NO"	NUMBER		NOT NULL,
	"ENROLL_DATE"	DATE	DEFAULT SYSDATE	NOT NULL
);


CREATE TABLE "REVIEW_BOARD" (
	"NO"	NUMBER		NOT NULL,
	"MEMBER_NO"	NUMBER		NOT NULL,
	"HOSPITAL_NO"	NUMBER		NOT NULL,
	"DEPARTMENT"	VARCHAR2(500)		NULL,
	"VISIT_DATE"	DATE		NULL,
	"TITLE"	VARCHAR2(2000)		NOT NULL,
	"CONTENT"	    CLOB		    NOT NULL,
	"RATING"	NUMBER		    NOT NULL,
	"ENROLL_DATE"	DATE	DEFAULT SYSDATE	NOT NULL,
	"MODIFY_DATE"	DATE		NULL,
	"DEL_YN"	CHAR(1)		DEFAULT 'N' NOT NULL
);

CREATE TABLE "REVIEW_ATTACHMENT" (
	"NO"	NUMBER		NOT NULL,
	"REVIEW_NO"	NUMBER		NOT NULL,
	"ORIGIN_NAME"	VARCHAR2(255)		NOT NULL,
	"PATH"	VARCHAR2(1000)		NOT NULL,
	"UPLOAD_DATE"	DATE	DEFAULT SYSDATE	NOT NULL,
	"DEL_YN"	CHAR(1)		DEFAULT 'N'    NOT NULL
);


CREATE TABLE "NOTICE_ATTACHMENT" (
	"NO"	NUMBER		NOT NULL,
	"NOTICE_NO"	NUMBER		NOT NULL,
	"ORIGIN_NAME"	VARCHAR2(255)		NOT NULL,
	"PATH"	VARCHAR2(1000)		NOT NULL,
	"UPLOAD_DATE"	DATE	DEFAULT SYSDATE	NOT NULL,
	"DEL_YN"	CHAR(1)		DEFAULT 'N'    NOT NULL
);

CREATE TABLE "BOARD_ATTACHMENT" (
	"NO"	NUMBER		NOT NULL,
	"BOARD_NO"	NUMBER		NOT NULL,
	"ORIGIN_NAME"	VARCHAR2(255)		NOT NULL,
	"PATH"	VARCHAR2(1000)		NOT NULL,
	"UPLOAD_DATE"	DATE	DEFAULT SYSDATE	NOT NULL,
	"DEL_YN"	CHAR(1)		DEFAULT 'N'    NOT NULL
);

CREATE TABLE "CITY" (
	"NO"	NUMBER		NOT NULL,
	"CITY_NAME"	VARCHAR2(100)		NOT NULL
);

CREATE TABLE "DISTRICT" (
	"NO"	NUMBER		NOT NULL,
	"CITY_NO"	NUMBER		NOT NULL,
	"DISTRICT_NAME"	VARCHAR2(100)		NOT NULL
);

CREATE TABLE "DONG" (
	"NO"	NUMBER		NOT NULL,
	"DISTRICT_NO"	NUMBER		NOT NULL,
	"DONG_NAME"	VARCHAR2(100)		NOT NULL
);

CREATE TABLE "TIMETABLE" (
	"NO"	NUMBER		NOT NULL,
	"MEMBER_NO"	NUMBER		NOT NULL,
	"PUSH_CODE"	NUMBER		NOT NULL,
	"DAYS"	NUMBER		NOT NULL,
	"TIME"	VARCHAR2(20)		NOT NULL
);

CREATE TABLE "PUSH_CODE" (
	"NO"	NUMBER		NOT NULL,
	"NAME"	VARCHAR2(200)		NOT NULL
);

CREATE TABLE "HOSPITAL_TIME" (
	"NO"	NUMBER		NOT NULL,
	"HOSPITAL_NO"	NUMBER		NOT NULL,
	"DAY_OF_WEEK"	VARCHAR2(10)		NULL,
	"O_TIME"	VARCHAR2(4)		NULL,
	"C_TIME"	VARCHAR2(4)		NULL
);


CREATE TABLE "PHARMACY_TIME" (
	"NO"	NUMBER		NOT NULL,
	"PHARMACY_NO"	NUMBER		NOT NULL,
	"DAY_OF_WEEK"	VARCHAR2(10)		NULL,
	"O_TIME"	VARCHAR2(4)		NULL,
	"C_TIME"	VARCHAR2(4)		NULL,
	"Y_LOCATION"	NUMBER		NULL
);

CREATE TABLE "PUBLIC_HEALTH_CENTER_TIME" (
	"NO"	NUMBER		NOT NULL,
	"CENTER_NO"	NUMBER		NOT NULL,
	"DAY_OF_WEEK"	VARCHAR2(10)		NULL,
	"O_TIME"	VARCHAR2(4)		NULL,
	"C_TIME"	VARCHAR2(4)		NULL
);

CREATE TABLE "WEIGHT_LOG" (
	"NO"	NUMBER		NOT NULL,
	"MEMBER_NO"	NUMBER		NOT NULL,
	"ENROLL_DATE"	DATE		NOT NULL,
	"AMOUNT"	NUMBER		NOT NULL
);

CREATE TABLE BOARD_RECOMMEND (
    BOARD_NO NUMBER NOT NULL,
    MEMBER_NO NUMBER NOT NULL,
    ENROLL_DATE DATE DEFAULT SYSDATE NOT NULL
);
CREATE TABLE REVIEW_RECOMMEND (
    REVIEW_NO NUMBER NOT NULL,
    MEMBER_NO NUMBER NOT NULL,
    ENROLL_DATE DATE DEFAULT SYSDATE NOT NULL
);

CREATE TABLE "LEVEL" (
    "LEVEL" NUMBER PRIMARY KEY,
    "REQUIRED_EXP" NUMBER NOT NULL
);

CREATE TABLE "CHALLENGER" (
    "NO" NUMBER NOT NULL,
    "TITLE" VARCHAR2(255) NOT NULL,
    "CONTENT" CLOB NOT NULL,
    "WRITER" NUMBER NOT NULL,
    "RECRUITMENT_START" TIMESTAMP NOT NULL, 
    "RECRUITMENT_END" TIMESTAMP NOT NULL,    
    "PERFORMANCE_START" TIMESTAMP NOT NULL, 
    "PERFORMANCE_END" TIMESTAMP NOT NULL,    
    "MAX_MEMBERS" NUMBER DEFAULT 1 NOT NULL,
    "STATUS" VARCHAR2(20) DEFAULT 'OPEN',
    "ENROLL_DATE" TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE "CHALLENGER_MEMBER" (
    "NO" NUMBER NOT NULL,
    "MEMBER_NO" NUMBER NOT NULL,
    "CHALLENGER_NO" NUMBER NOT NULL,
    "ATTAINMENT_RATE" NUMBER(5,2) DEFAULT 0, 
    "COMPLETED_DAYS" NUMBER DEFAULT 0, 
    "JOINED_AT" TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE "CHALLENGER_POST" (
    "NO" NUMBER NOT NULL,
    "CHALLENGER_NO" NUMBER NOT NULL,
    "MEMBER_NO" NUMBER NOT NULL,
    "TITLE" VARCHAR2(255) NOT NULL,
    "CONTENT" CLOB NOT NULL,
    "IMAGE_URL" VARCHAR2(255), 
    "ENROLL_DATE" TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);


CREATE TABLE "DASHBOARD" (
	"NO"	NUMBER		NOT NULL,
	"MEMBER_NO"	NUMBER		NOT NULL,
	"NAME"	VARCHAR(1000)		NOT NULL,
	"VISIBLE_YN"	CHAR(1)	DEFAULT 'Y'	NOT NULL
);

CREATE TABLE "BANNER" (
	"NO"	NUMBER		NOT NULL,
	"WRITER"	NUMBER		NOT NULL,
	"TITLE"     VARCHAR(1000)   NOT NULL,
	"IMAGE_URL"	VARCHAR(2000)		NULL,
	"SHOW_YN"	CHAR(1)		NOT NULL,
	"ENROLL_DATE"	DATE	DEFAULT SYSDATE	NOT NULL,
	"MODIFY_DATE"	DATE		NULL,
	"DEL_YN"	CHAR(1)	DEFAULT 'N'	NOT NULL
);

CREATE TABLE "REPORTED_REVIEW_COMMENT" (
    "NO"	NUMBER		NOT NULL,
	"REPORT_TYPE"	NUMBER		NOT NULL,
	"COMMENT_NO"	NUMBER		NOT NULL,
	"MEMBER_NO"	NUMBER		NOT NULL,
	"ENROLL_DATE"	DATE	DEFAULT SYSDATE	NOT NULL
);
CREATE TABLE "REVIEW_COMMENT" (
	"NO"	NUMBER		NOT NULL,
	"MEMBER_NO"	NUMBER		NOT NULL,
	"REVIEW_NO"	NUMBER		NOT NULL,
	"CONTENT"	VARCHAR2(2000)		NOT NULL,
	"ENROLL_DATE"	DATE  DEFAULT SYSDATE		NOT NULL,
	"MODIFY_DATE"	DATE		NULL,
	"DEL_YN"	CHAR(1)		DEFAULT 'N' NOT NULL
);
CREATE TABLE "NOTIFICATION_SETTINGS" (
    NO NUMBER PRIMARY KEY,
    MEMBER_NO NUMBER,
    ALL_PUSH CHAR(1) DEFAULT 'Y' CHECK (ALL_PUSH IN ('Y', 'N')),
    DIET_PUSH CHAR(1) DEFAULT 'Y' CHECK (DIET_PUSH IN ('Y', 'N')),
    WATER_PUSH CHAR(1) DEFAULT 'Y' CHECK (WATER_PUSH IN ('Y', 'N')),
    EXERCISE_PUSH CHAR(1) DEFAULT 'Y' CHECK (EXERCISE_PUSH IN ('Y', 'N')),
    COMMENT_PUSH CHAR(1) DEFAULT 'Y' CHECK (COMMENT_PUSH IN ('Y', 'N')),
    BLOOD_PRESSURE_PUSH CHAR(1) DEFAULT 'Y' CHECK (BLOOD_PRESSURE_PUSH IN ('Y', 'N')),
    BLOOD_SUGAR_PUSH CHAR(1) DEFAULT 'Y' CHECK (BLOOD_SUGAR_PUSH IN ('Y', 'N')),
    INSULIN_PUSH CHAR(1) DEFAULT 'Y' CHECK (INSULIN_PUSH IN ('Y', 'N')),
    CONSTRAINT fk_member FOREIGN KEY (MEMBER_NO) REFERENCES MEMBER (NO)
);
CREATE TABLE "NOTIFICATION" (
    "NO"            NUMBER PRIMARY KEY,
    "MEMBER_NO"     NUMBER NOT NULL,
    "CONTENT"       VARCHAR2(1000) NOT NULL,
    "CHECK_YN"      CHAR(1) DEFAULT 'N' NOT NULL,
    "DEL_YN"        CHAR(1) DEFAULT 'N' NOT NULL,
    "ENROLL_DATE"   DATE    DEFAULT SYSDATE,
    CONSTRAINT fk_member_no FOREIGN KEY (MEMBER_NO) REFERENCES MEMBER (NO)
);




-- PK

ALTER TABLE "BLOOD_PRESSURE" ADD CONSTRAINT "PK_BLOOD_PRESSURE" PRIMARY KEY (
	"NO"
);

ALTER TABLE "BLOOD_SUGAR" ADD CONSTRAINT "PK_BLOOD_SUGAR" PRIMARY KEY (
	"NO"
);

ALTER TABLE "SLEEP" ADD CONSTRAINT "PK_SLEEP" PRIMARY KEY (
	"NO"
);

ALTER TABLE "INSULIN" ADD CONSTRAINT "PK_INSULIN" PRIMARY KEY (
	"NO"
);

ALTER TABLE "REPORTED_HONEY_TIP" ADD CONSTRAINT "PK_REPORTED_HONEY_TIP" PRIMARY KEY (
	"NO"
);

ALTER TABLE "HOSPITAL" ADD CONSTRAINT "PK_HOSPITAL" PRIMARY KEY (
	"NO"
);

ALTER TABLE "REPORT_TYPE" ADD CONSTRAINT "PK_REPORT_TYPE" PRIMARY KEY (
	"NO"
);

ALTER TABLE "REPORTED_BOARD_COMMENT" ADD CONSTRAINT "PK_REPORTED_BOARD_COMMENT" PRIMARY KEY (
	"NO"
);

ALTER TABLE "NOTICE" ADD CONSTRAINT "PK_NOTICE" PRIMARY KEY (
	"NO"
);

ALTER TABLE "DEPARTMENT" ADD CONSTRAINT "PK_DEPARTMENT" PRIMARY KEY (
	"NO"
);

ALTER TABLE "ALC_TYPE" ADD CONSTRAINT "PK_ALC_TYPE" PRIMARY KEY (
	"NO"
);

ALTER TABLE "BODYPART" ADD CONSTRAINT "PK_BODYPART" PRIMARY KEY (
	"NO"
);

ALTER TABLE "BOARD" ADD CONSTRAINT "PK_BOARD" PRIMARY KEY (
	"NO"
);

ALTER TABLE "DIET" ADD CONSTRAINT "PK_DIET" PRIMARY KEY (
	"NO"
);

ALTER TABLE "WATER_LOG" ADD CONSTRAINT "PK_WATER_LOG" PRIMARY KEY (
	"NO"
);

ALTER TABLE "FOOD" ADD CONSTRAINT "PK_FOOD" PRIMARY KEY (
	"NO"
);

ALTER TABLE "BOARD_COMMENT" ADD CONSTRAINT "PK_BOARD_COMMENT" PRIMARY KEY (
	"NO"
);

ALTER TABLE "DETAIL_BODYPART" ADD CONSTRAINT "PK_DETAIL_BODYPART" PRIMARY KEY (
	"NO"
);

ALTER TABLE "SYMPTOM" ADD CONSTRAINT "PK_SYMPTOM" PRIMARY KEY (
	"NO"
);

ALTER TABLE "BODY_SYMPTOM" ADD CONSTRAINT "PK_BODY_SYMPTOM" PRIMARY KEY (
	"NO"
);

ALTER TABLE "PUBLIC_HEALTH_CENTER" ADD CONSTRAINT "PK_PUBLIC_HEALTH_CENTER" PRIMARY KEY (
	"NO"
);

ALTER TABLE "MEDICATION" ADD CONSTRAINT "PK_MEDICATION" PRIMARY KEY (
	"NO"
);

ALTER TABLE "MEAL_LOG" ADD CONSTRAINT "PK_MEAL_LOG" PRIMARY KEY (
	"NO"
);

ALTER TABLE "DRUG_FORM" ADD CONSTRAINT "PK_DRUG_FORM" PRIMARY KEY (
	"NO"
);

ALTER TABLE "DRUG_COLOR" ADD CONSTRAINT "PK_DRUG_COLOR" PRIMARY KEY (
	"NO"
);


ALTER TABLE "USER_MEDICATION" ADD CONSTRAINT "PK_USER_MEDICATION" PRIMARY KEY (
	"NO"
);

ALTER TABLE "CATEGORY" ADD CONSTRAINT "PK_CATEGORY" PRIMARY KEY (
	"NO"
);

ALTER TABLE "PHARMACY" ADD CONSTRAINT "PK_PHARMACY" PRIMARY KEY (
	"NO"
);

ALTER TABLE "HOSPITAL_DEPARTMENT" ADD CONSTRAINT "PK_HOSPITAL_DEPARTMENT" PRIMARY KEY (
	"NO"
);

ALTER TABLE "PUSH_NOTIFICATION" ADD CONSTRAINT "PK_PUSH_NOTIFICATION" PRIMARY KEY (
	"NO"
);

ALTER TABLE "MEAL_CODE" ADD CONSTRAINT "PK_MEAL_CODE" PRIMARY KEY (
	"NO"
);

ALTER TABLE "PUSH_SETTING" ADD CONSTRAINT "PK_PUSH_SETTING" PRIMARY KEY (
	"NO"
);

ALTER TABLE "RECORD_ALC" ADD CONSTRAINT "PK_RECORD_ALC" PRIMARY KEY (
	"NO"
);

ALTER TABLE "RECORD_CIGARETTE" ADD CONSTRAINT "PK_RECORD_CIGARETTE" PRIMARY KEY (
	"NO"
);

ALTER TABLE "DOCTOR" ADD CONSTRAINT "PK_DOCTOR" PRIMARY KEY (
	"NO"
);

ALTER TABLE "ADMIN" ADD CONSTRAINT "PK_ADMIN" PRIMARY KEY (
	"NO"
);

ALTER TABLE "COMPANY" ADD CONSTRAINT "PK_COMPANY" PRIMARY KEY (
	"NO"
);

ALTER TABLE "COMPANY_DEPT" ADD CONSTRAINT "PK_COMPANY_DEPT" PRIMARY KEY (
	"NO"
);

ALTER TABLE "REPORTED_REVIEW" ADD CONSTRAINT "PK_REPORTED_REVIEW" PRIMARY KEY (
	"NO"
);

ALTER TABLE "REVIEW_BOARD" ADD CONSTRAINT "PK_REVIEW_BOARD" PRIMARY KEY (
	"NO"
);

ALTER TABLE "NOTICE_ATTACHMENT" ADD CONSTRAINT "PK_NOTICE_ATTACHMENT" PRIMARY KEY (
	"NO"
);

ALTER TABLE "BOARD_ATTACHMENT" ADD CONSTRAINT "PK_BOARD_ATTACHMENT" PRIMARY KEY (
	"NO"
);

ALTER TABLE "CITY" ADD CONSTRAINT "PK_CITY" PRIMARY KEY (
	"NO"
);

ALTER TABLE "DISTRICT" ADD CONSTRAINT "PK_DISTRICT" PRIMARY KEY (
	"NO"
);

ALTER TABLE "DONG" ADD CONSTRAINT "PK_DONG" PRIMARY KEY (
	"NO"
);

ALTER TABLE "TIMETABLE" ADD CONSTRAINT "PK_TIMETABLE" PRIMARY KEY (
	"NO"
);

ALTER TABLE "PUSH_CODE" ADD CONSTRAINT "PK_PUSH_CODE" PRIMARY KEY (
	"NO"
);

ALTER TABLE "HOSPITAL_TIME" ADD CONSTRAINT "PK_HOSPITAL_TIME" PRIMARY KEY (
	"NO"
);

ALTER TABLE "PHARMACY_TIME" ADD CONSTRAINT "PK_PHARMACY_TIME" PRIMARY KEY (
	"NO"
);

ALTER TABLE "PUBLIC_HEALTH_CENTER_TIME" ADD CONSTRAINT "PK_PUBLIC_HEALTH_CENTER_TIME" PRIMARY KEY (
	"NO"
);

ALTER TABLE "WEIGHT_LOG" ADD CONSTRAINT "PK_WEIGHT_LOG" PRIMARY KEY (
	"NO"
);

ALTER TABLE "CHALLENGER_POST" ADD CONSTRAINT "PK_CHALLENGER_POST" PRIMARY KEY ("NO");

ALTER TABLE "CHALLENGER" ADD CONSTRAINT "PK_CHALLENGER" PRIMARY KEY ("NO");

ALTER TABLE "CHALLENGER_MEMBER" ADD CONSTRAINT "PK_CHALLENGER_MEMBER" PRIMARY KEY ("NO");

ALTER TABLE "DASHBOARD" ADD CONSTRAINT "PK_DASHBOARD" PRIMARY KEY ("NO");

ALTER TABLE "BANNER" ADD CONSTRAINT "PK_BANNER" PRIMARY KEY ("NO");

ALTER TABLE "REVIEW_COMMENT" ADD CONSTRAINT "PK_REVIEW_COMMENT" PRIMARY KEY ("NO");

ALTER TABLE "REPORTED_REVIEW_COMMENT" ADD CONSTRAINT "PK_REPORTED_REVIEW_COMMENT" PRIMARY KEY ("NO");


-- FK
ALTER TABLE "BLOOD_PRESSURE" ADD CONSTRAINT "FK_MEMBER_TO_BLOOD_PRESSURE_1" FOREIGN KEY (
	"MEMBER_NO"
)
REFERENCES "MEMBER" (
	"NO"
);

ALTER TABLE "BLOOD_SUGAR" ADD CONSTRAINT "FK_MEMBER_TO_BLOOD_SUGAR_1" FOREIGN KEY (
	"MEMBER_NO"
)
REFERENCES "MEMBER" (
	"NO"
);

ALTER TABLE "SLEEP" ADD CONSTRAINT "FK_MEMBER_TO_SLEEP_1" FOREIGN KEY (
	"MEMBER_NO"
)
REFERENCES "MEMBER" (
	"NO"
);

ALTER TABLE "INSULIN" ADD CONSTRAINT "FK_MEMBER_TO_INSULIN_1" FOREIGN KEY (
	"MEMBER_NO"
)
REFERENCES "MEMBER" (
	"NO"
);

ALTER TABLE "REPORTED_HONEY_TIP" ADD CONSTRAINT "FK_REPORT_TYPE_TO_REPORTED_HONEY_TIP_1" FOREIGN KEY (
	"REPORT_TYPE"
)
REFERENCES "REPORT_TYPE" (
	"NO"
);

ALTER TABLE "REPORTED_HONEY_TIP" ADD CONSTRAINT "FK_BOARD_TO_REPORTED_HONEY_TIP_1" FOREIGN KEY (
	"BOARD_NO"
)
REFERENCES "BOARD" (
	"NO"
);

ALTER TABLE "REPORTED_BOARD_COMMENT" ADD CONSTRAINT "FK_REPORT_TYPE_TO_REPORTED_BOARD_COMMENT_1" FOREIGN KEY (
	"REPORT_TYPE"
)
REFERENCES "REPORT_TYPE" (
	"NO"
);

ALTER TABLE "REPORTED_BOARD_COMMENT" ADD CONSTRAINT "FK_BOARD_COMMENT_TO_REPORTED_BOARD_COMMENT_1" FOREIGN KEY (
	"COMMENT_NO"
)
REFERENCES "BOARD_COMMENT" (
	"NO"
);

ALTER TABLE "REPORTED_BOARD_COMMENT" ADD CONSTRAINT "FK_MEMBER_TO_REPORTED_BOARD_COMMENT_2" FOREIGN KEY (
	"MEMBER_NO"
)
REFERENCES "MEMBER" (
	"NO"
);

ALTER TABLE "NOTICE" ADD CONSTRAINT "FK_ADMIN_TO_NOTICE_1" FOREIGN KEY (
	"WRITER"
)
REFERENCES "ADMIN" (
	"NO"
);

ALTER TABLE "BOARD" ADD CONSTRAINT "FK_CATEGORY_TO_BOARD_1" FOREIGN KEY (
	"CATEGORY_NO"
)
REFERENCES "CATEGORY" (
	"NO"
);

ALTER TABLE "BOARD" ADD CONSTRAINT "FK_MEMBER_TO_BOARD_1" FOREIGN KEY (
	"MEMBER_NO"
)
REFERENCES "MEMBER" (
	"NO"
);

ALTER TABLE "DIET" ADD CONSTRAINT "FK_MEMBER_TO_DIET_1" FOREIGN KEY (
	"MEMBER_NO"
)
REFERENCES "MEMBER" (
	"NO"
);

ALTER TABLE "DIET" ADD CONSTRAINT "FK_MEAL_CODE_TO_DIET_1" FOREIGN KEY (
	"MEAL_CODE"
)
REFERENCES "MEAL_CODE" (
	"NO"
);

ALTER TABLE "WATER_LOG" ADD CONSTRAINT "FK_MEMBER_TO_WATER_LOG_1" FOREIGN KEY (
	"MEMBER_NO"
)
REFERENCES "MEMBER" (
	"NO"
);

ALTER TABLE "BOARD_COMMENT" ADD CONSTRAINT "FK_MEMBER_TO_BOARD_COMMENT_1" FOREIGN KEY (
	"MEMBER_NO"
)
REFERENCES "MEMBER" (
	"NO"
);

ALTER TABLE "BOARD_COMMENT" ADD CONSTRAINT "FK_BOARD_TO_BOARD_COMMENT_1" FOREIGN KEY (
	"BOARD_NO"
)
REFERENCES "BOARD" (
	"NO"
);

ALTER TABLE "DETAIL_BODYPART" ADD CONSTRAINT "FK_BODYPART_TO_DETAIL_BODYPART_1" FOREIGN KEY (
	"BODYPART"
)
REFERENCES "BODYPART" (
	"NO"
);

ALTER TABLE "SYMPTOM" ADD CONSTRAINT "FK_DETAIL_BODYPART_TO_SYMPTOM_1" FOREIGN KEY (
	"DETAILPART"
)
REFERENCES "DETAIL_BODYPART" (
	"NO"
);

ALTER TABLE "BODY_SYMPTOM" ADD CONSTRAINT "FK_SYMPTOM_TO_BODY_SYMPTOM_1" FOREIGN KEY (
	"SYMPTOM"
)
REFERENCES "SYMPTOM" (
	"NO"
);



ALTER TABLE "MEAL_LOG" ADD CONSTRAINT "FK_DIET_TO_MEAL_LOG_1" FOREIGN KEY (
	"DIET_NO"
)
REFERENCES "DIET" (
	"NO"
);

ALTER TABLE "USER_MEDICATION" ADD CONSTRAINT "FK_MEDICATION_TO_USER_MEDICATION_1" FOREIGN KEY (
	"MEDICATION"
)
REFERENCES "MEDICATION" (
	"NO"
);

ALTER TABLE "USER_MEDICATION" ADD CONSTRAINT "FK_MEMBER_TO_USER_MEDICATION_1" FOREIGN KEY (
	"MEMBER"
)
REFERENCES "MEMBER" (
	"NO"
	
);

ALTER TABLE "MEDICATION" ADD CONSTRAINT "FK_MEDICATION_COLOR1" FOREIGN KEY (
	"COLOR1"
)
REFERENCES "DRUG_COLOR" (
	"NO"
);

ALTER TABLE "MEDICATION" ADD CONSTRAINT "FK_MEDICATION_COLOR2" FOREIGN KEY (
	"COLOR2"
)
REFERENCES "DRUG_COLOR" (
	"NO"
);

ALTER TABLE "MEDICATION" ADD CONSTRAINT "FK_MEDICATION_FORM" FOREIGN KEY (
	"FORM"
)
REFERENCES "DRUG_FORM" (
	"NO"
);

ALTER TABLE "HOSPITAL_DEPARTMENT" ADD CONSTRAINT "FK_HOSPITAL_TO_HOSPITAL_DEPARTMENT_1" FOREIGN KEY (
	"HOSPITAL"
)
REFERENCES "HOSPITAL" (
	"NO"
);

ALTER TABLE "HOSPITAL_DEPARTMENT" ADD CONSTRAINT "FK_DEPARTMENT_TO_HOSPITAL_DEPARTMENT_1" FOREIGN KEY (
	"DEPT"
)
REFERENCES "DEPARTMENT" (
	"NO"
);

ALTER TABLE "PUSH_NOTIFICATION" ADD CONSTRAINT "FK_PUSH_CODE_TO_PUSH_NOTIFICATION_1" FOREIGN KEY (
	"PUSH_CODE"
)
REFERENCES "PUSH_CODE" (
	"NO"
);

ALTER TABLE "PUSH_NOTIFICATION" ADD CONSTRAINT "FK_MEMBER_TO_PUSH_NOTIFICATION_1" FOREIGN KEY (
	"MEMBER_NO"
)
REFERENCES "MEMBER" (
	"NO"
);

ALTER TABLE "PUSH_SETTING" ADD CONSTRAINT "FK_MEMBER_TO_PUSH_SETTING_1" FOREIGN KEY (
	"MEMBER_NO"
)
REFERENCES "MEMBER" (
	"NO"
);

ALTER TABLE "PUSH_SETTING" ADD CONSTRAINT "FK_PUSH_CODE_TO_PUSH_SETTING_1" FOREIGN KEY (
	"PUSH_CODE"
)
REFERENCES "PUSH_CODE" (
	"NO"
);

ALTER TABLE "RECOMMENDATION" ADD CONSTRAINT "FK_BOARD_TO_RECOMMENDATION_1" FOREIGN KEY (
	"BOARD_NO"
)
REFERENCES "BOARD" (
	"NO"
);

ALTER TABLE "RECOMMENDATION" ADD CONSTRAINT "FK_MEMBER_TO_RECOMMENDATION_1" FOREIGN KEY (
	"MEMBER_NO"
)
REFERENCES "MEMBER" (
	"NO"
);

ALTER TABLE "RECORD_ALC" ADD CONSTRAINT "FK_MEMBER_TO_RECORD_ALC_1" FOREIGN KEY (
	"MEMBER_NO"
)
REFERENCES "MEMBER" (
	"NO"
);

ALTER TABLE "RECORD_CIGARETTE" ADD CONSTRAINT "FK_MEMBER_TO_RECORD_CIGARETTE_1" FOREIGN KEY (
	"MEMBER_NO"
)
REFERENCES "MEMBER" (
	"NO"
);

ALTER TABLE "DOCTOR" ADD CONSTRAINT "FK_HOSPITAL_TO_DOCTOR_1" FOREIGN KEY (
	"HOSPITAL"
)
REFERENCES "HOSPITAL" (
	"NO"
);

ALTER TABLE "DOCTOR" ADD CONSTRAINT "FK_DEPARTMENT_TO_DOCTOR_1" FOREIGN KEY (
	"DEPARTMENT"
)
REFERENCES "DEPARTMENT" (
	"NO"
);

ALTER TABLE "COMPANY_DEPT" ADD CONSTRAINT "FK_COMPANY_TO_COMPANY_DEPT_1" FOREIGN KEY (
	"COMPANY_NO"
)
REFERENCES "COMPANY" (
	"NO"
);

ALTER TABLE "REPORTED_REVIEW" ADD CONSTRAINT "FK_REPORT_TYPE_TO_REPORTED_REVIEW_1" FOREIGN KEY (
	"REPORT_TYPE"
)
REFERENCES "REPORT_TYPE" (
	"NO"
);

ALTER TABLE "REPORTED_REVIEW" ADD CONSTRAINT "FK_REVIEW_BOARD_TO_REPORTED_REVIEW_1" FOREIGN KEY (
	"REVIEW_NO"
)
REFERENCES "REVIEW_BOARD" (
	"NO"
);

ALTER TABLE "REVIEW_BOARD" ADD CONSTRAINT "FK_MEMBER_TO_REVIEW_BOARD_1" FOREIGN KEY (
	"MEMBER_NO"
)
REFERENCES "MEMBER" (
	"NO"
);

ALTER TABLE "REVIEW_BOARD" ADD CONSTRAINT "FK_HOSPITAL_TO_REVIEW_BOARD_1" FOREIGN KEY (
	"HOSPITAL_NO"
)
REFERENCES "HOSPITAL" (
	"NO"
);



ALTER TABLE "NOTICE_ATTACHMENT" ADD CONSTRAINT "FK_NOTICE_TO_NOTICE_ATTACHMENT_1" FOREIGN KEY (
	"NOTICE_NO"
)
REFERENCES "NOTICE" (
	"NO"
);

ALTER TABLE "BOARD_ATTACHMENT" ADD CONSTRAINT "FK_BOARD_TO_BOARD_ATTACHMENT_1" FOREIGN KEY (
	"BOARD_NO"
)
REFERENCES "BOARD" (
	"NO"
);

ALTER TABLE "DISTRICT" ADD CONSTRAINT "FK_CITY_TO_DISTRICT_1" FOREIGN KEY (
	"CITY_NO"
)
REFERENCES "CITY" (
	"NO"
);

ALTER TABLE "DONG" ADD CONSTRAINT "FK_DISTRICT_TO_DONG_1" FOREIGN KEY (
	"DISTRICT_NO"
)
REFERENCES "DISTRICT" (
	"NO"
);

ALTER TABLE "TIMETABLE" ADD CONSTRAINT "FK_MEMBER_TO_TIMETABLE_1" FOREIGN KEY (
	"MEMBER_NO"
)
REFERENCES "MEMBER" (
	"NO"
);

ALTER TABLE "TIMETABLE" ADD CONSTRAINT "FK_PUSH_CODE_TO_TIMETABLE_1" FOREIGN KEY (
	"PUSH_CODE"
)
REFERENCES "PUSH_CODE" (
	"NO"
);

ALTER TABLE "HOSPITAL_TIME" ADD CONSTRAINT "FK_HOSPITAL_TO_HOSPITAL_TIME_1" FOREIGN KEY (
	"HOSPITAL_NO"
)
REFERENCES "HOSPITAL" (
	"NO"
);

ALTER TABLE "PHARMACY_TIME" ADD CONSTRAINT "FK_PHARMACY_TO_PHARMACY_TIME_1" FOREIGN KEY (
	"PHARMACY_NO"
)
REFERENCES "PHARMACY" (
	"NO"
);

ALTER TABLE "PUBLIC_HEALTH_CENTER_TIME" ADD CONSTRAINT "FK_PUBLIC_HEALTH_CENTER_TO_PUBLIC_HEALTH_CENTER_TIME_1" FOREIGN KEY (
	"CENTER_NO"
)
REFERENCES "PUBLIC_HEALTH_CENTER" (
	"NO"
);

ALTER TABLE "WEIGHT_LOG" ADD CONSTRAINT "FK_MEMBER_TO_WEIGHT_LOG_1" FOREIGN KEY (
	"MEMBER_NO"
)
REFERENCES "MEMBER" (
	"NO"
);

ALTER TABLE "REVIEW_ATTACHMENT" ADD CONSTRAINT "FK_REVIEW_BOARD_TO_REVIEW_ATTACHMENT_1" FOREIGN KEY (
	"REVIEW_NO"
)
REFERENCES "REVIEW_BOARD" (
	"NO"
);
ALTER TABLE "REVIEW_COMMENT" ADD CONSTRAINT "FK_MEMBER_TO_REVIEW_COMMENT_1" FOREIGN KEY (
	"MEMBER_NO"
)
REFERENCES "MEMBER" (
	"NO"
);



ALTER TABLE "REPORTED_REVIEW_COMMENT" ADD CONSTRAINT "FK_REPORT_TYPE_TO_REPORTED_REVIEW_COMMENT_1" FOREIGN KEY (
	"REPORT_TYPE"
)
REFERENCES "REPORT_TYPE" (
	"NO"
);

ALTER TABLE "REPORTED_REVIEW_COMMENT" ADD CONSTRAINT "FK_REVIEW_COMMENT_TO_REPORTED_REVIEW_COMMENT_1" FOREIGN KEY (
	"COMMENT_NO"
)
REFERENCES "REVIEW_COMMENT" (
	"NO"
);

ALTER TABLE "REPORTED_REVIEW_COMMENT" ADD CONSTRAINT "FK_MEMBER_TO_REPORTED_REVIEW_COMMENT_1" FOREIGN KEY (
	"MEMBER_NO"
)
REFERENCES "MEMBER" (
	"NO"
);
ALTER TABLE "REVIEW_COMMENT" ADD CONSTRAINT "FK_REVIEW_TO_REVIEW_COMMENT_1" FOREIGN KEY (
	"REVIEW_NO"
)
REFERENCES "REVIEW_BOARD" (
	"NO"
);


ALTER TABLE "CHALLENGER_POST" ADD CONSTRAINT "FK_CHALLENGER_TO_POST" 
FOREIGN KEY ("CHALLENGER_NO") REFERENCES "CHALLENGER" ("NO") ON DELETE CASCADE;

ALTER TABLE "CHALLENGER_POST" ADD CONSTRAINT "FK_MEMBER_TO_POST" 
FOREIGN KEY ("MEMBER_NO") REFERENCES "MEMBER" ("NO") ON DELETE CASCADE;

ALTER TABLE "CHALLENGER" ADD CONSTRAINT "FK_MEMBER_TO_CHALLENGER" 
FOREIGN KEY ("WRITER") REFERENCES "MEMBER" ("NO") ON DELETE CASCADE;

ALTER TABLE "CHALLENGER_MEMBER" ADD CONSTRAINT "FK_MEMBER_TO_CHALLENGER_MEMBER" 
FOREIGN KEY ("MEMBER_NO") REFERENCES "MEMBER" ("NO") ON DELETE CASCADE;

ALTER TABLE "CHALLENGER_MEMBER" ADD CONSTRAINT "FK_CHALLENGER_TO_MEMBER" 
FOREIGN KEY ("CHALLENGER_NO") REFERENCES "CHALLENGER" ("NO") ON DELETE CASCADE;

ALTER TABLE BOARD_RECOMMEND
ADD CONSTRAINT PK_BOARD_RECOMMEND PRIMARY KEY (BOARD_NO, MEMBER_NO);

ALTER TABLE BOARD_RECOMMEND
ADD CONSTRAINT FK_BOARD_RECOMMEND_BOARD FOREIGN KEY (BOARD_NO)
REFERENCES BOARD(NO);

ALTER TABLE BOARD_RECOMMEND
ADD CONSTRAINT FK_BOARD_RECOMMEND_MEMBER FOREIGN KEY (MEMBER_NO)
REFERENCES MEMBER(NO);

ALTER TABLE REVIEW_RECOMMEND
ADD CONSTRAINT PK_REVIEW_RECOMMEND PRIMARY KEY (REVIEW_NO, MEMBER_NO);

ALTER TABLE REVIEW_RECOMMEND
ADD CONSTRAINT FK_REVIEW_RECOMMEND_REVIEW_BOARD FOREIGN KEY (REVIEW_NO)
REFERENCES REVIEW_BOARD(NO);

ALTER TABLE REVIEW_RECOMMEND
ADD CONSTRAINT FK_REVIEW_RECOMMEND_MEMBER FOREIGN KEY (MEMBER_NO)
REFERENCES MEMBER(NO);

ALTER TABLE "DASHBOARD" 
ADD CONSTRAINT "FK_MEMBER_TO_DASHBOARD_1" FOREIGN KEY ("MEMBER_NO")
REFERENCES "MEMBER" ("NO");

ALTER TABLE "BANNER" 
ADD CONSTRAINT "FK_ADMIN_TO_BANNER_1" FOREIGN KEY ("WRITER")
REFERENCES "ADMIN" ("NO");



CREATE OR REPLACE FUNCTION GET_BOARD_ATTACHMENT_NO
RETURN NUMBER
AS
  N NUMBER;
BEGIN

  SELECT SEQ_BOARD_ATTACHMENT.NEXTVAL
  INTO N
  FROM DUAL;
  
  RETURN N;
END;
/
CREATE OR REPLACE FUNCTION GET_NOTICE_ATTACHMENT_NO
RETURN NUMBER
AS
  N NUMBER;
BEGIN

  SELECT SEQ_NOTICE_ATTACHMENT.NEXTVAL
  INTO N
  FROM DUAL;
  
  RETURN N;
END;
/

CREATE OR REPLACE FUNCTION GET_REVIEW_ATTACHMENT_NO
RETURN NUMBER
AS
  N NUMBER;
BEGIN

  SELECT SEQ_REVIEW_ATTACHMENT.NEXTVAL
  INTO N
  FROM DUAL;
  
  RETURN N;
END;
/

