Vagrant.configure("2") do |config|

  # 운영체제 설정
  config.vm.box = "ubuntu/focal64"

  # vm 설정
  config.vm.provider "virtualbox" do |vb|
    vb.memory = "1024"
    vb.cpus = 1
  end

  # network 설정
  # config.vm.network "forwarded_port", guest: 80, host: 8787
  config.vm.network "private_network", ip: "192.168.33.10"

  # provisioning 설정
  config.vm.provision "shell", inline: <<-SHELL
    sudo apt update
    sudo apt install -y openjdk-17-jdk
  SHELL

end
